/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 * 
 * 
 *
 * This file provides RXPMD access functions for BCM56960_A0
 */

#include <sal/sal_types.h>
#include <bsl/bsl.h>
#include <bcmpkt/bcmpkt_rxpmd.h>
#include <bcmpkt/bcmpkt_rxpmd_internal.h>

#define MASK(_bn) (((uint32_t)0x1<<(_bn))-1)
#define WORD_FIELD_GET(_d,_s,_l) (((_d) >> (_s)) & MASK(_l))
#define WORD_FIELD_SET(_d,_s,_l,_v) (_d)=(((_d) & ~(MASK(_l) << (_s))) | (((_v) & MASK(_l)) << (_s)))
#define WORD_FIELD_MASK(_d,_s,_l) (_d)=((_d) | (MASK(_l) << (_s)))
/*******************************************************************************
 * SWFORMAT:  RXPMD
 * BLOCKS:
 * SIZE:     416
 */
static void bcmpkt_rxpmd_unicast_queue_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_UNICAST_QUEUE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[2], 6, 1, val);
}

static uint32_t bcmpkt_rxpmd_unicast_queue_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_UNICAST_QUEUE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[2], 6, 1);
}

static void bcmpkt_rxpmd_queue_num_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_QUEUE_NUM with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[2], 0, 6, val);
}

static uint32_t bcmpkt_rxpmd_queue_num_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_QUEUE_NUM on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[2], 0, 6);
}

static void bcmpkt_rxpmd_cpu_cos_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_CPU_COS with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[2], 0, 6, val);
}

static uint32_t bcmpkt_rxpmd_cpu_cos_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_CPU_COS on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[2], 0, 6);
}

static void bcmpkt_rxpmd_hgi_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_HGI with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[3], 30, 2, val);
}

static uint32_t bcmpkt_rxpmd_hgi_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_HGI on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[3], 30, 2);
}

static void bcmpkt_rxpmd_matched_rule_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_MATCHED_RULE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[3], 22, 8, val);
}

static uint32_t bcmpkt_rxpmd_matched_rule_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_MATCHED_RULE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[3], 22, 8);
}

static void bcmpkt_rxpmd_pkt_length_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_PKT_LENGTH with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[3], 8, 14, val);
}

static uint32_t bcmpkt_rxpmd_pkt_length_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_PKT_LENGTH on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[3], 8, 14);
}

static void bcmpkt_rxpmd_src_port_num_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SRC_PORT_NUM with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[3], 0, 8, val);
}

static uint32_t bcmpkt_rxpmd_src_port_num_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SRC_PORT_NUM on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[3], 0, 8);
}

static void bcmpkt_rxpmd_inner_vid_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_INNER_VID with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 18, 12, val);
}

static uint32_t bcmpkt_rxpmd_inner_vid_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_INNER_VID on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 18, 12);
}

static void bcmpkt_rxpmd_inner_cfi_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_INNER_CFI with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 30, 1, val);
}

static uint32_t bcmpkt_rxpmd_inner_cfi_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_INNER_CFI on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 30, 1);
}

static void bcmpkt_rxpmd_inner_pri_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_INNER_PRI with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[8], 0, 3, val);
}

static uint32_t bcmpkt_rxpmd_inner_pri_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_INNER_PRI on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[8], 0, 3);
}

static void bcmpkt_rxpmd_outer_vid_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_OUTER_VID with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[2], 20, 12, val);
}

static uint32_t bcmpkt_rxpmd_outer_vid_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_OUTER_VID on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[2], 20, 12);
}

static void bcmpkt_rxpmd_outer_cfi_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_OUTER_CFI with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 9, 1, val);
}

static uint32_t bcmpkt_rxpmd_outer_cfi_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_OUTER_CFI on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 9, 1);
}

static void bcmpkt_rxpmd_outer_pri_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_OUTER_PRI with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 10, 3, val);
}

static uint32_t bcmpkt_rxpmd_outer_pri_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_OUTER_PRI on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 10, 3);
}

static void bcmpkt_rxpmd_special_packet_indicator_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SPECIAL_PACKET_INDICATOR with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 15, 1, val);
}

static uint32_t bcmpkt_rxpmd_special_packet_indicator_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SPECIAL_PACKET_INDICATOR on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 15, 1);
}

static void bcmpkt_rxpmd_special_packet_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SPECIAL_PACKET_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 0, 3, val);
}

static uint32_t bcmpkt_rxpmd_special_packet_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SPECIAL_PACKET_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 0, 3);
}

static void bcmpkt_rxpmd_change_dscp_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_CHANGE_DSCP with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 6, 1, val);
}

static uint32_t bcmpkt_rxpmd_change_dscp_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_CHANGE_DSCP on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 6, 1);
}

static void bcmpkt_rxpmd_dscp_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_DSCP with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 0, 6, val);
}

static uint32_t bcmpkt_rxpmd_dscp_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_DSCP on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 0, 6);
}

static void bcmpkt_rxpmd_change_ecn_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_CHANGE_ECN with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 31, 1, val);
}

static uint32_t bcmpkt_rxpmd_change_ecn_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_CHANGE_ECN on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 31, 1);
}

static void bcmpkt_rxpmd_ecn_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_ECN with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 29, 2, val);
}

static uint32_t bcmpkt_rxpmd_ecn_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_ECN on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 29, 2);
}

static void bcmpkt_rxpmd_timestamp_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_TIMESTAMP_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 18, 2, val);
}

static uint32_t bcmpkt_rxpmd_timestamp_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_TIMESTAMP_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 18, 2);
}

static void bcmpkt_rxpmd_timestamp_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_TIMESTAMP with value %u on device BCM56960_A0.\n"), val));
    data[10] = val;
}

static uint32_t bcmpkt_rxpmd_timestamp_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_TIMESTAMP on device BCM56960_A0.\n")));
    return data[10];
}

static void bcmpkt_rxpmd_timestamp_hi_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_TIMESTAMP_HI with value %u on device BCM56960_A0.\n"), val));
    data[12] = val;
}

static uint32_t bcmpkt_rxpmd_timestamp_hi_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_TIMESTAMP_HI on device BCM56960_A0.\n")));
    return data[12];
}

static void bcmpkt_rxpmd_mtp_index_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_MTP_INDEX with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 24, 5, val);
}

static uint32_t bcmpkt_rxpmd_mtp_index_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_MTP_INDEX on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 24, 5);
}

static void bcmpkt_rxpmd_bpdu_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_BPDU with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 17, 1, val);
}

static uint32_t bcmpkt_rxpmd_bpdu_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_BPDU on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 17, 1);
}

static void bcmpkt_rxpmd_replication_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_REPLICATION with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 13, 1, val);
}

static uint32_t bcmpkt_rxpmd_replication_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_REPLICATION on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 13, 1);
}

static void bcmpkt_rxpmd_l3only_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_L3ONLY with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 12, 1, val);
}

static uint32_t bcmpkt_rxpmd_l3only_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_L3ONLY on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 12, 1);
}

static void bcmpkt_rxpmd_ip_routed_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_IP_ROUTED with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 11, 1, val);
}

static uint32_t bcmpkt_rxpmd_ip_routed_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_IP_ROUTED on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 11, 1);
}

static void bcmpkt_rxpmd_src_higig_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SRC_HIGIG with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 10, 1, val);
}

static uint32_t bcmpkt_rxpmd_src_higig_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SRC_HIGIG on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 10, 1);
}

static void bcmpkt_rxpmd_src_higig2_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SRC_HIGIG2 with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 9, 1, val);
}

static uint32_t bcmpkt_rxpmd_src_higig2_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SRC_HIGIG2 on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 9, 1);
}

static void bcmpkt_rxpmd_uc_sw_copy_dropped_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_UC_SW_COPY_DROPPED with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 8, 1, val);
}

static uint32_t bcmpkt_rxpmd_uc_sw_copy_dropped_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_UC_SW_COPY_DROPPED on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 8, 1);
}

static void bcmpkt_rxpmd_switch_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SWITCH with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 7, 1, val);
}

static uint32_t bcmpkt_rxpmd_switch_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SWITCH on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 7, 1);
}

static void bcmpkt_rxpmd_sd_tag_present_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_SD_TAG_PRESENT with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 6, 1, val);
}

static uint32_t bcmpkt_rxpmd_sd_tag_present_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_SD_TAG_PRESENT on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 6, 1);
}

static void bcmpkt_rxpmd_ing_itag_action_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_ING_ITAG_ACTION with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 4, 2, val);
}

static uint32_t bcmpkt_rxpmd_ing_itag_action_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_ING_ITAG_ACTION on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 4, 2);
}

static void bcmpkt_rxpmd_ing_otag_action_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_ING_OTAG_ACTION with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 2, 2, val);
}

static uint32_t bcmpkt_rxpmd_ing_otag_action_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_ING_OTAG_ACTION on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 2, 2);
}

static void bcmpkt_rxpmd_incoming_tag_status_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_INCOMING_TAG_STATUS with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 0, 2, val);
}

static uint32_t bcmpkt_rxpmd_incoming_tag_status_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_INCOMING_TAG_STATUS on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 0, 2);
}

static void bcmpkt_rxpmd_one_step_1588_ing_update_done_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_ONE_STEP_1588_ING_UPDATE_DONE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[12], 27, 1, val);
}

static uint32_t bcmpkt_rxpmd_one_step_1588_ing_update_done_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_ONE_STEP_1588_ING_UPDATE_DONE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[12], 27, 1);
}

static void bcmpkt_rxpmd_eh_tag_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TAG with value %u on device BCM56960_A0.\n"), val));
    data[12] = val;
}

static uint32_t bcmpkt_rxpmd_eh_tag_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TAG on device BCM56960_A0.\n")));
    return data[12];
}

static void bcmpkt_rxpmd_eh_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[12], 28, 4, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[12], 28, 4);
}

static void bcmpkt_rxpmd_eh_type_0_eh_seg_sel_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_0_EH_SEG_SEL with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 0) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 21, 3, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_0_eh_seg_sel_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_0_EH_SEG_SEL on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 0) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 21, 3);
}

static void bcmpkt_rxpmd_eh_type_0_eh_tag_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_0_EH_TAG_TYPE with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 0) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 19, 2, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_0_eh_tag_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_0_EH_TAG_TYPE on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 0) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 19, 2);
}

static void bcmpkt_rxpmd_eh_type_0_eh_queue_tag_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_0_EH_QUEUE_TAG with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 0) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 0, 16, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_0_eh_queue_tag_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_0_EH_QUEUE_TAG on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 0) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 0, 16);
}

static void bcmpkt_rxpmd_eh_type_1_classid_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_1_CLASSID_TYPE with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 1) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 23, 4, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_1_classid_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_1_CLASSID_TYPE on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 1) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 23, 4);
}

static void bcmpkt_rxpmd_eh_type_1_l3_iif_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_1_L3_IIF with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 1) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 9, 14, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_1_l3_iif_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_1_L3_IIF on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 1) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 9, 14);
}

static void bcmpkt_rxpmd_eh_type_1_classid_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_1_CLASSID with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 1) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 0, 9, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_1_classid_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_1_CLASSID on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 1) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 0, 9);
}

static void bcmpkt_rxpmd_eh_type_2_classid_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_2_CLASSID_TYPE with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 2) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 23, 4, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_2_classid_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_2_CLASSID_TYPE on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 2) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 23, 4);
}

static void bcmpkt_rxpmd_eh_type_2_classid_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_2_CLASSID with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 2) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 14, 9, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_2_classid_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_2_CLASSID on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 2) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 14, 9);
}

static void bcmpkt_rxpmd_eh_type_2_eh_queue_tag_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_EH_TYPE_2_EH_QUEUE_TAG with value %u on device BCM56960_A0.\n"), val));
    if (bcmpkt_rxpmd_eh_type_get(data) != 2) {
        LOG_ERROR(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return;
    }
    WORD_FIELD_SET(data[12], 0, 14, val);
}

static uint32_t bcmpkt_rxpmd_eh_type_2_eh_queue_tag_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_EH_TYPE_2_EH_QUEUE_TAG on device BCM56960_A0.\n")));
    if (bcmpkt_rxpmd_eh_type_get(data) != 2) {
        LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("View doesn't match!\n")));
        return 0;
    }
    return WORD_FIELD_GET(data[12], 0, 14);
}

static void bcmpkt_rxpmd_rx_bfd_start_offset_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_RX_BFD_START_OFFSET with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[12], 14, 8, val);
}

static uint32_t bcmpkt_rxpmd_rx_bfd_start_offset_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_RX_BFD_START_OFFSET on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[12], 14, 8);
}

static void bcmpkt_rxpmd_rx_bfd_start_offset_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_RX_BFD_START_OFFSET_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[12], 12, 2, val);
}

static uint32_t bcmpkt_rxpmd_rx_bfd_start_offset_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_RX_BFD_START_OFFSET_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[12], 12, 2);
}

static void bcmpkt_rxpmd_rx_bfd_session_index_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_RX_BFD_SESSION_INDEX with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[12], 0, 12, val);
}

static uint32_t bcmpkt_rxpmd_rx_bfd_session_index_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_RX_BFD_SESSION_INDEX on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[12], 0, 12);
}

static void bcmpkt_rxpmd_reason_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_REASON_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[2], 16, 4, val);
}

static uint32_t bcmpkt_rxpmd_reason_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_REASON_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[2], 16, 4);
}

static void bcmpkt_rxpmd_do_not_change_ttl_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_DO_NOT_CHANGE_TTL with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 16, 1, val);
}

static uint32_t bcmpkt_rxpmd_do_not_change_ttl_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_DO_NOT_CHANGE_TTL on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 16, 1);
}

static void bcmpkt_rxpmd_loopback_packet_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_LOOPBACK_PACKET_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 20, 3, val);
}

static uint32_t bcmpkt_rxpmd_loopback_packet_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_LOOPBACK_PACKET_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 20, 3);
}

static void bcmpkt_rxpmd_regen_crc_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_REGEN_CRC with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[8], 4, 1, val);
}

static uint32_t bcmpkt_rxpmd_regen_crc_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_REGEN_CRC on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[8], 4, 1);
}

static void bcmpkt_rxpmd_tunnel_decap_type_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_TUNNEL_DECAP_TYPE with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 13, 4, val);
}

static uint32_t bcmpkt_rxpmd_tunnel_decap_type_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_TUNNEL_DECAP_TYPE on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 13, 4);
}

static void bcmpkt_rxpmd_hg2_ext_hdr_valid_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_HG2_EXT_HDR_VALID with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[11], 14, 1, val);
}

static uint32_t bcmpkt_rxpmd_hg2_ext_hdr_valid_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_HG2_EXT_HDR_VALID on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[11], 14, 1);
}

static void bcmpkt_rxpmd_vntag_action_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_VNTAG_ACTION with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[9], 7, 2, val);
}

static uint32_t bcmpkt_rxpmd_vntag_action_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_VNTAG_ACTION on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[9], 7, 2);
}

static void bcmpkt_rxpmd_dvp_nhi_sel_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_DVP_NHI_SEL with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[8], 3, 1, val);
}

static uint32_t bcmpkt_rxpmd_dvp_nhi_sel_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_DVP_NHI_SEL on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[8], 3, 1);
}

static void bcmpkt_rxpmd_vfi_valid_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_VFI_VALID with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[8], 24, 1, val);
}

static uint32_t bcmpkt_rxpmd_vfi_valid_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_VFI_VALID on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[8], 24, 1);
}

static void bcmpkt_rxpmd_replication_or_nhop_index_set(uint32_t *data, uint32_t val)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Set field BCMPKT_RXPMD_REPLICATION_OR_NHOP_INDEX with value %u on device BCM56960_A0.\n"), val));
    WORD_FIELD_SET(data[8], 5, 17, val);
}

static uint32_t bcmpkt_rxpmd_replication_or_nhop_index_get(uint32_t *data)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_REPLICATION_OR_NHOP_INDEX on device BCM56960_A0.\n")));
    return WORD_FIELD_GET(data[8], 5, 17);
}

static uint32_t bcmpkt_rxpmd_size_get(uint32_t *data, uint32_t **addr)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get BCMPKT_RXPMD_SIZE on device BCM56960_A0.\n")));
    return 13;
}

static uint32_t bcmpkt_rxpmd_reason_get(uint32_t *data, uint32_t **addr)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_REASON address on device BCM56960_A0.\n")));
    *addr = data + 0;
    return 2;
}

static uint32_t bcmpkt_rxpmd_module_hdr_get(uint32_t *data, uint32_t **addr)
{
    LOG_DEBUG(BSL_LS_BCMPKT_RXPMD, (BSL_META("Get field BCMPKT_RXPMD_MODULE_HDR address on device BCM56960_A0.\n")));
    *addr = data + 4;
    return 4;
}

/*******************************************************************************
 * SWFORMAT:  RX_REASON
 * BLOCKS:
 * SIZE:     64
 */
void bcm56960_a0_rx_reason_encode(const bcmpkt_rx_reasons_t *reasons, uint32_t *data)
{
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_UVLAN)) {
        data[1] |= (0x1 << 0);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_SLF)) {
        data[1] |= (0x1 << 1);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_DLF)) {
        data[1] |= (0x1 << 2);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_L2MOVE)) {
        data[1] |= (0x1 << 3);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_L2CPU)) {
        data[1] |= (0x1 << 4);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_SFLOW_SRC)) {
        data[1] |= (0x1 << 5);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_SFLOW_DST)) {
        data[1] |= (0x1 << 6);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_L3SRC_MISS)) {
        data[1] |= (0x1 << 7);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_L3DST_MISS)) {
        data[1] |= (0x1 << 8);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_L3SRC_MOVE)) {
        data[1] |= (0x1 << 9);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_MC_MISS)) {
        data[1] |= (0x1 << 10);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_IPMC_MISS)) {
        data[1] |= (0x1 << 11);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_FFP)) {
        data[1] |= (0x1 << 12);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_L3HDR_ERR)) {
        data[1] |= (0x1 << 13);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_PROTOCOL_PKT)) {
        data[1] |= (0x1 << 14);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_DOS_ATTACK)) {
        data[1] |= (0x1 << 15);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_MARTIAN_ADDR)) {
        data[1] |= (0x1 << 16);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_TUNNEL_ERR)) {
        data[1] |= (0x1 << 17);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_SFLOW_FLEX)) {
        data[1] |= (0x1 << 18);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_ICMP_REDIRECT)) {
        data[1] |= (0x1 << 19);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_L3_SLOWPATH)) {
        data[1] |= (0x1 << 20);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_PARITY_ERROR)) {
        data[1] |= (0x1 << 21);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_L3_MTU_CHECK_FAIL)) {
        data[1] |= (0x1 << 22);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_HGHDR_ERROR)) {
        data[1] |= (0x1 << 23);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MCIDX_ERROR)) {
        data[1] |= (0x1 << 24);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_VFP)) {
        data[1] |= (0x1 << 25);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CBSM_PREVENTED)) {
        data[1] |= (0x1 << 26);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MAC_BIND_FAIL)) {
        data[1] |= (0x1 << 27);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_LABEL_MISS)) {
        data[1] |= (0x1 << 28);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_INVALID_ACTION)) {
        data[1] |= (0x1 << 29);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_INVALID_PAYLOAD)) {
        data[1] |= (0x1 << 30);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_TTL_CHECK_FAIL)) {
        data[1] |= (0x1 << 31);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_SEQ_NUM_FAIL)) {
        data[0] |= (0x1 << 0);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_PBT_NONUC_PKT)) {
        data[0] |= (0x1 << 1);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_L3_NEXT_HOP)) {
        data[0] |= (0x1 << 2);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_UNKNOWN_ACH_ERROR)) {
        data[0] |= (0x1 << 3);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MY_STATION)) {
        data[0] |= (0x1 << 4);
    }

    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV_DOT1P_DROP)) {
        WORD_FIELD_SET(data[0], 5, 3, 1);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV_VIF_MISS)) {
        WORD_FIELD_SET(data[0], 5, 3, 2);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV_RPF_MISS)) {
        WORD_FIELD_SET(data[0], 5, 3, 3);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV_VNTAG_ERROR)) {
        WORD_FIELD_SET(data[0], 5, 3, 4);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV_VNTAG_PRESENT)) {
        WORD_FIELD_SET(data[0], 5, 3, 5);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV_VNTAG_NOT_PRESENT)) {
        WORD_FIELD_SET(data[0], 5, 3, 6);
    }
    /*! For mask set ONLY. */
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NIV)) {
        WORD_FIELD_SET(data[0], 5, 3, 7);
    }

    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_VXLT_MISS)) {
        data[0] |= (0x1 << 8);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_TIME_SYNC)) {
        data[0] |= (0x1 << 9);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_OAM_SLOWPATH)) {
        data[0] |= (0x1 << 10);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_TUNNEL_DECAP_ECN_ERROR)) {
        data[0] |= (0x1 << 11);
    }

    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_HDR_ERROR)) {
        WORD_FIELD_SET(data[0], 12, 3, 1);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_LOOKUP_MISS)) {
        WORD_FIELD_SET(data[0], 12, 3, 2);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_RPF_CHECK_FAIL)) {
        WORD_FIELD_SET(data[0], 12, 3, 3);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_SLOWPATH)) {
        WORD_FIELD_SET(data[0], 12, 3, 4);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_CORE_IS_IS_PKT)) {
        WORD_FIELD_SET(data[0], 12, 3, 5);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_HOP_COUNT_CHECK_FAIL)) {
        WORD_FIELD_SET(data[0], 12, 3, 6);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL_NICKNAME_TABLE)) {
        WORD_FIELD_SET(data[0], 12, 3, 7);
    }
    /*! For mask set ONLY. */
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_TRILL)) {
        WORD_FIELD_SET(data[0], 12, 3, 7);
    }

    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_L2GRE_SIP_MISS)) {
        data[0] |= (0x1 << 15);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_L2GRE_VPNID_MISS)) {
        data[0] |= (0x1 << 16);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_BFD_SLOWPATH)) {
        data[0] |= (0x1 << 17);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_BFD_ERROR)) {
        data[0] |= (0x1 << 18);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_PACKET_TRACE_TO_CPU)) {
        data[0] |= (0x1 << 19);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_ICNM)) {
        data[0] |= (0x1 << 20);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_ILLEGAL_RESERVED_LABEL)) {
        data[0] |= (0x1 << 21);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_MPLS_ALERT_LABEL)) {
        data[0] |= (0x1 << 22);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_QCN_CNM_PRP)) {
        data[0] |= (0x1 << 23);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_QCN_CNM_PRP_DLF)) {
        data[0] |= (0x1 << 24);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_VXLAN_SIP_MISS)) {
        data[0] |= (0x1 << 25);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_VXLAN_VN_ID_MISS)) {
        data[0] |= (0x1 << 26);
    }
    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_FCOE_ZONE_CHECK_FAIL)) {
        data[0] |= (0x1 << 27);
    }

    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NAT_TCP_UDP_MISS)) {
        WORD_FIELD_SET(data[0], 28, 3, 1);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NAT_ICMP_MISS)) {
        WORD_FIELD_SET(data[0], 28, 3, 2);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NAT_FRAGMENT)) {
        WORD_FIELD_SET(data[0], 28, 3, 3);
    }
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NAT_OTHER_MISS)) {
        WORD_FIELD_SET(data[0], 28, 3, 4);
    }
    /*! For mask set ONLY. */
    if (BCMPKT_RX_REASON_GET(*reasons,  BCMPKT_RX_REASON_NAT)) {
        WORD_FIELD_SET(data[0], 28, 3, 7);
    }

    if (BCMPKT_RX_REASON_GET(*reasons, BCMPKT_RX_REASON_CPU_IPMC_INTERFACE_MISMATCH)) {
        data[0] |= (0x1 << 31);
    }
}
void bcm56960_a0_rx_reason_decode(const uint32_t *data, bcmpkt_rx_reasons_t *reasons)
{
    uint32_t val;
    COMPILER_REFERENCE(val);
    if (data[1] & (0x1 << 0)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_UVLAN);
    }
    if (data[1] & (0x1 << 1)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_SLF);
    }
    if (data[1] & (0x1 << 2)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_DLF);
    }
    if (data[1] & (0x1 << 3)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_L2MOVE);
    }
    if (data[1] & (0x1 << 4)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_L2CPU);
    }
    if (data[1] & (0x1 << 5)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_SFLOW_SRC);
    }
    if (data[1] & (0x1 << 6)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_SFLOW_DST);
    }
    if (data[1] & (0x1 << 7)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_L3SRC_MISS);
    }
    if (data[1] & (0x1 << 8)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_L3DST_MISS);
    }
    if (data[1] & (0x1 << 9)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_L3SRC_MOVE);
    }
    if (data[1] & (0x1 << 10)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_MC_MISS);
    }
    if (data[1] & (0x1 << 11)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_IPMC_MISS);
    }
    if (data[1] & (0x1 << 12)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_FFP);
    }
    if (data[1] & (0x1 << 13)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_L3HDR_ERR);
    }
    if (data[1] & (0x1 << 14)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_PROTOCOL_PKT);
    }
    if (data[1] & (0x1 << 15)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_DOS_ATTACK);
    }
    if (data[1] & (0x1 << 16)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_MARTIAN_ADDR);
    }
    if (data[1] & (0x1 << 17)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_TUNNEL_ERR);
    }
    if (data[1] & (0x1 << 18)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_SFLOW_FLEX);
    }
    if (data[1] & (0x1 << 19)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_ICMP_REDIRECT);
    }
    if (data[1] & (0x1 << 20)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_L3_SLOWPATH);
    }
    if (data[1] & (0x1 << 21)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_PARITY_ERROR);
    }
    if (data[1] & (0x1 << 22)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_L3_MTU_CHECK_FAIL);
    }
    if (data[1] & (0x1 << 23)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_HGHDR_ERROR);
    }
    if (data[1] & (0x1 << 24)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MCIDX_ERROR);
    }
    if (data[1] & (0x1 << 25)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_VFP);
    }
    if (data[1] & (0x1 << 26)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CBSM_PREVENTED);
    }
    if (data[1] & (0x1 << 27)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MAC_BIND_FAIL);
    }
    if (data[1] & (0x1 << 28)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_LABEL_MISS);
    }
    if (data[1] & (0x1 << 29)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_INVALID_ACTION);
    }
    if (data[1] & (0x1 << 30)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_INVALID_PAYLOAD);
    }
    if (data[1] & (0x1 << 31)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_TTL_CHECK_FAIL);
    }
    if (data[0] & (0x1 << 0)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_SEQ_NUM_FAIL);
    }
    if (data[0] & (0x1 << 1)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_PBT_NONUC_PKT);
    }
    if (data[0] & (0x1 << 2)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_L3_NEXT_HOP);
    }
    if (data[0] & (0x1 << 3)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_UNKNOWN_ACH_ERROR);
    }
    if (data[0] & (0x1 << 4)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MY_STATION);
    }

    val = WORD_FIELD_GET(data[0], 5, 3);
    if (val) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_NIV);
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_NIV + val);
    }

    if (data[0] & (0x1 << 8)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_VXLT_MISS);
    }
    if (data[0] & (0x1 << 9)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_TIME_SYNC);
    }
    if (data[0] & (0x1 << 10)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_OAM_SLOWPATH);
    }
    if (data[0] & (0x1 << 11)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_TUNNEL_DECAP_ECN_ERROR);
    }

    val = WORD_FIELD_GET(data[0], 12, 3);
    if (val) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_TRILL);
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_TRILL + val);
    }

    if (data[0] & (0x1 << 15)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_L2GRE_SIP_MISS);
    }
    if (data[0] & (0x1 << 16)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_L2GRE_VPNID_MISS);
    }
    if (data[0] & (0x1 << 17)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_BFD_SLOWPATH);
    }
    if (data[0] & (0x1 << 18)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_BFD_ERROR);
    }
    if (data[0] & (0x1 << 19)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_PACKET_TRACE_TO_CPU);
    }
    if (data[0] & (0x1 << 20)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_ICNM);
    }
    if (data[0] & (0x1 << 21)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_ILLEGAL_RESERVED_LABEL);
    }
    if (data[0] & (0x1 << 22)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_MPLS_ALERT_LABEL);
    }
    if (data[0] & (0x1 << 23)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_QCN_CNM_PRP);
    }
    if (data[0] & (0x1 << 24)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_QCN_CNM_PRP_DLF);
    }
    if (data[0] & (0x1 << 25)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_VXLAN_SIP_MISS);
    }
    if (data[0] & (0x1 << 26)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_VXLAN_VN_ID_MISS);
    }
    if (data[0] & (0x1 << 27)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_FCOE_ZONE_CHECK_FAIL);
    }

    val = WORD_FIELD_GET(data[0], 28, 3);
    if (val) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_NAT);
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_NAT + val);
    }

    if (data[0] & (0x1 << 31)) {
        BCMPKT_RX_REASON_SET(*reasons, BCMPKT_RX_REASON_CPU_IPMC_INTERFACE_MISMATCH);
    }
}

const bcmpkt_rxpmd_fget_t bcm56960_a0_rxpmd_fget = {
    {
        bcmpkt_rxpmd_unicast_queue_get,
        bcmpkt_rxpmd_queue_num_get,
        bcmpkt_rxpmd_cpu_cos_get,
        bcmpkt_rxpmd_hgi_get,
        bcmpkt_rxpmd_matched_rule_get,
        bcmpkt_rxpmd_pkt_length_get,
        bcmpkt_rxpmd_src_port_num_get,
        bcmpkt_rxpmd_inner_vid_get,
        bcmpkt_rxpmd_inner_cfi_get,
        bcmpkt_rxpmd_inner_pri_get,
        bcmpkt_rxpmd_outer_vid_get,
        bcmpkt_rxpmd_outer_cfi_get,
        bcmpkt_rxpmd_outer_pri_get,
        bcmpkt_rxpmd_special_packet_indicator_get,
        bcmpkt_rxpmd_special_packet_type_get,
        bcmpkt_rxpmd_change_dscp_get,
        bcmpkt_rxpmd_dscp_get,
        bcmpkt_rxpmd_change_ecn_get,
        bcmpkt_rxpmd_ecn_get,
        bcmpkt_rxpmd_timestamp_type_get,
        bcmpkt_rxpmd_timestamp_get,
        bcmpkt_rxpmd_timestamp_hi_get,
        bcmpkt_rxpmd_mtp_index_get,
        bcmpkt_rxpmd_bpdu_get,
        bcmpkt_rxpmd_replication_get,
        bcmpkt_rxpmd_l3only_get,
        bcmpkt_rxpmd_ip_routed_get,
        bcmpkt_rxpmd_src_higig_get,
        bcmpkt_rxpmd_src_higig2_get,
        bcmpkt_rxpmd_uc_sw_copy_dropped_get,
        bcmpkt_rxpmd_switch_get,
        bcmpkt_rxpmd_sd_tag_present_get,
        bcmpkt_rxpmd_ing_itag_action_get,
        bcmpkt_rxpmd_ing_otag_action_get,
        bcmpkt_rxpmd_incoming_tag_status_get,
        bcmpkt_rxpmd_one_step_1588_ing_update_done_get,
        bcmpkt_rxpmd_eh_tag_get,
        bcmpkt_rxpmd_eh_type_get,
        bcmpkt_rxpmd_eh_type_0_eh_seg_sel_get,
        bcmpkt_rxpmd_eh_type_0_eh_tag_type_get,
        bcmpkt_rxpmd_eh_type_0_eh_queue_tag_get,
        bcmpkt_rxpmd_eh_type_1_classid_type_get,
        bcmpkt_rxpmd_eh_type_1_l3_iif_get,
        bcmpkt_rxpmd_eh_type_1_classid_get,
        bcmpkt_rxpmd_eh_type_2_classid_type_get,
        bcmpkt_rxpmd_eh_type_2_classid_get,
        bcmpkt_rxpmd_eh_type_2_eh_queue_tag_get,
        bcmpkt_rxpmd_rx_bfd_start_offset_get,
        bcmpkt_rxpmd_rx_bfd_start_offset_type_get,
        bcmpkt_rxpmd_rx_bfd_session_index_get,
        bcmpkt_rxpmd_reason_type_get,
        bcmpkt_rxpmd_do_not_change_ttl_get,
        NULL,
        NULL,
        NULL,
        bcmpkt_rxpmd_loopback_packet_type_get,
        bcmpkt_rxpmd_regen_crc_get,
        NULL,
        bcmpkt_rxpmd_tunnel_decap_type_get,
        NULL,
        NULL,
        bcmpkt_rxpmd_hg2_ext_hdr_valid_get,
        bcmpkt_rxpmd_vntag_action_get,
        bcmpkt_rxpmd_dvp_nhi_sel_get,
        bcmpkt_rxpmd_vfi_valid_get,
        bcmpkt_rxpmd_replication_or_nhop_index_get,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    }
};


const bcmpkt_rxpmd_fset_t bcm56960_a0_rxpmd_fset = {
    {
        bcmpkt_rxpmd_unicast_queue_set,
        bcmpkt_rxpmd_queue_num_set,
        bcmpkt_rxpmd_cpu_cos_set,
        bcmpkt_rxpmd_hgi_set,
        bcmpkt_rxpmd_matched_rule_set,
        bcmpkt_rxpmd_pkt_length_set,
        bcmpkt_rxpmd_src_port_num_set,
        bcmpkt_rxpmd_inner_vid_set,
        bcmpkt_rxpmd_inner_cfi_set,
        bcmpkt_rxpmd_inner_pri_set,
        bcmpkt_rxpmd_outer_vid_set,
        bcmpkt_rxpmd_outer_cfi_set,
        bcmpkt_rxpmd_outer_pri_set,
        bcmpkt_rxpmd_special_packet_indicator_set,
        bcmpkt_rxpmd_special_packet_type_set,
        bcmpkt_rxpmd_change_dscp_set,
        bcmpkt_rxpmd_dscp_set,
        bcmpkt_rxpmd_change_ecn_set,
        bcmpkt_rxpmd_ecn_set,
        bcmpkt_rxpmd_timestamp_type_set,
        bcmpkt_rxpmd_timestamp_set,
        bcmpkt_rxpmd_timestamp_hi_set,
        bcmpkt_rxpmd_mtp_index_set,
        bcmpkt_rxpmd_bpdu_set,
        bcmpkt_rxpmd_replication_set,
        bcmpkt_rxpmd_l3only_set,
        bcmpkt_rxpmd_ip_routed_set,
        bcmpkt_rxpmd_src_higig_set,
        bcmpkt_rxpmd_src_higig2_set,
        bcmpkt_rxpmd_uc_sw_copy_dropped_set,
        bcmpkt_rxpmd_switch_set,
        bcmpkt_rxpmd_sd_tag_present_set,
        bcmpkt_rxpmd_ing_itag_action_set,
        bcmpkt_rxpmd_ing_otag_action_set,
        bcmpkt_rxpmd_incoming_tag_status_set,
        bcmpkt_rxpmd_one_step_1588_ing_update_done_set,
        bcmpkt_rxpmd_eh_tag_set,
        bcmpkt_rxpmd_eh_type_set,
        bcmpkt_rxpmd_eh_type_0_eh_seg_sel_set,
        bcmpkt_rxpmd_eh_type_0_eh_tag_type_set,
        bcmpkt_rxpmd_eh_type_0_eh_queue_tag_set,
        bcmpkt_rxpmd_eh_type_1_classid_type_set,
        bcmpkt_rxpmd_eh_type_1_l3_iif_set,
        bcmpkt_rxpmd_eh_type_1_classid_set,
        bcmpkt_rxpmd_eh_type_2_classid_type_set,
        bcmpkt_rxpmd_eh_type_2_classid_set,
        bcmpkt_rxpmd_eh_type_2_eh_queue_tag_set,
        bcmpkt_rxpmd_rx_bfd_start_offset_set,
        bcmpkt_rxpmd_rx_bfd_start_offset_type_set,
        bcmpkt_rxpmd_rx_bfd_session_index_set,
        bcmpkt_rxpmd_reason_type_set,
        bcmpkt_rxpmd_do_not_change_ttl_set,
        NULL,
        NULL,
        NULL,
        bcmpkt_rxpmd_loopback_packet_type_set,
        bcmpkt_rxpmd_regen_crc_set,
        NULL,
        bcmpkt_rxpmd_tunnel_decap_type_set,
        NULL,
        NULL,
        bcmpkt_rxpmd_hg2_ext_hdr_valid_set,
        bcmpkt_rxpmd_vntag_action_set,
        bcmpkt_rxpmd_dvp_nhi_sel_set,
        bcmpkt_rxpmd_vfi_valid_set,
        bcmpkt_rxpmd_replication_or_nhop_index_set,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    }
};


const bcmpkt_rxpmd_figet_t bcm56960_a0_rxpmd_figet = {
    {
        bcmpkt_rxpmd_size_get,
        bcmpkt_rxpmd_reason_get,
        bcmpkt_rxpmd_module_hdr_get
    }
};

static shr_enum_map_t bcm56960_a0_rxpmd_view_types[] = {
    {"eh_type_0", 0},
    {"eh_type_1", 1},
    {"eh_type_2", 2},
    {NULL, -1},
};

static int bcm56960_a0_rxpmd_view_infos[BCMPKT_RXPMD_FID_COUNT] = {
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, -1, -1, -1, -1,  0,  0,  0,  1,  1,  1,  2,  2,  2, -1,
     -1, -1, -1, -1, -2, -2, -2, -1, -1, -2, -1, -2, -2, -1, -1, -1,
     -1, -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
};


void bcm56960_a0_rxpmd_view_info_get(bcmpkt_pmd_view_info_t *info)
{
    info->view_infos = bcm56960_a0_rxpmd_view_infos;
    info->view_types = bcm56960_a0_rxpmd_view_types;
    info->view_type_get = bcmpkt_rxpmd_eh_type_get;
}
