/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 */

/*
 * Chip inclusion and exclusion support within the BCMDRD can be
 * specified as a combination of the following defines:
 *
 *     (1) #define BCMDRD_CONFIG_INCLUDE_<CHIPNAME> [1|0]
 *             -- Include or exclude all revisions of the given device
 *             Example: #define BCMDRD_CONFIG_INCLUDE_BCM56960   1
 *
 *     (2) #define BCMDRD_CONFIG_INCLUDE_<CHIPNAME>_<REV>X [1|0]
 *             -- Include or exclude all versions of the given revision
 *             Example: #define BCMDRD_CONFIG_INCLUDE_BCM56960_Ax 0
 *                      #define BCMDRD_CONFIG_INCLUde_BCM56960_Bx 1
 *
 *     (3) #define BCMDRD_CONFIG_INCLUDE_<EXACT_CHIP> [1|0]
 *             -- Include or exclude an exact device
 *             Example: #define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
 *                      #define BCMDRD_CONFIG_INCLUDE_BCM56960_A1 0
 *
 *
 * The value of BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT is used for any
 * chips which are left unspecified. Set this value to 1 or 0 to
 * include or exclude all chips by default.
 */

#ifndef BCMDRD_CONFIG_CHIPS_H
#define BCMDRD_CONFIG_CHIPS_H

/* This determines whether a chip is included or excluded by default */
#ifndef BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#define BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT 1
#endif

/*
 * Default configuration and dependencies for all chips
 */

/*
 * BCM56960
 */

/* Sets the default include state if it was not given */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960
#define BCMDRD_CONFIG_INCLUDE_BCM56960 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
/* Resolve revision dependencies */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_Ax
#define BCMDRD_CONFIG_INCLUDE_BCM56960_Ax BCMDRD_CONFIG_INCLUDE_BCM56960
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 BCMDRD_CONFIG_INCLUDE_BCM56960_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A1 BCMDRD_CONFIG_INCLUDE_BCM56960_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_Bx
#define BCMDRD_CONFIG_INCLUDE_BCM56960_Bx BCMDRD_CONFIG_INCLUDE_BCM56960
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_B0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_B0 BCMDRD_CONFIG_INCLUDE_BCM56960_Bx
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_B1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_B1 BCMDRD_CONFIG_INCLUDE_BCM56960_Bx
#endif
/* Resolve all interchip dependencies */
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A1 == 1
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_B0 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_B1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif


/*
 * BCM56961
 */

/* Sets the default include state if it was not given */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961
#define BCMDRD_CONFIG_INCLUDE_BCM56961 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
/* Resolve revision dependencies */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961_Ax
#define BCMDRD_CONFIG_INCLUDE_BCM56961_Ax BCMDRD_CONFIG_INCLUDE_BCM56961
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56961_A0 BCMDRD_CONFIG_INCLUDE_BCM56961_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961_A1
#define BCMDRD_CONFIG_INCLUDE_BCM56961_A1 BCMDRD_CONFIG_INCLUDE_BCM56961_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961_Bx
#define BCMDRD_CONFIG_INCLUDE_BCM56961_Bx BCMDRD_CONFIG_INCLUDE_BCM56961
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961_B0
#define BCMDRD_CONFIG_INCLUDE_BCM56961_B0 BCMDRD_CONFIG_INCLUDE_BCM56961_Bx
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56961_B1
#define BCMDRD_CONFIG_INCLUDE_BCM56961_B1 BCMDRD_CONFIG_INCLUDE_BCM56961_Bx
#endif
/* Resolve all interchip dependencies */
#if BCMDRD_CONFIG_INCLUDE_BCM56961_A0 == 1
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56961_A1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56961_B0 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56961_B1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif


/*
 * BCM56962
 */

/* Sets the default include state if it was not given */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962
#define BCMDRD_CONFIG_INCLUDE_BCM56962 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
/* Resolve revision dependencies */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962_Ax
#define BCMDRD_CONFIG_INCLUDE_BCM56962_Ax BCMDRD_CONFIG_INCLUDE_BCM56962
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56962_A0 BCMDRD_CONFIG_INCLUDE_BCM56962_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962_A1
#define BCMDRD_CONFIG_INCLUDE_BCM56962_A1 BCMDRD_CONFIG_INCLUDE_BCM56962_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962_Bx
#define BCMDRD_CONFIG_INCLUDE_BCM56962_Bx BCMDRD_CONFIG_INCLUDE_BCM56962
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962_B0
#define BCMDRD_CONFIG_INCLUDE_BCM56962_B0 BCMDRD_CONFIG_INCLUDE_BCM56962_Bx
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56962_B1
#define BCMDRD_CONFIG_INCLUDE_BCM56962_B1 BCMDRD_CONFIG_INCLUDE_BCM56962_Bx
#endif
/* Resolve all interchip dependencies */
#if BCMDRD_CONFIG_INCLUDE_BCM56962_A0 == 1
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56962_A1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56962_B0 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56962_B1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif


/*
 * BCM56963
 */

/* Sets the default include state if it was not given */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963
#define BCMDRD_CONFIG_INCLUDE_BCM56963 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
/* Resolve revision dependencies */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963_Ax
#define BCMDRD_CONFIG_INCLUDE_BCM56963_Ax BCMDRD_CONFIG_INCLUDE_BCM56963
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56963_A0 BCMDRD_CONFIG_INCLUDE_BCM56963_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963_A1
#define BCMDRD_CONFIG_INCLUDE_BCM56963_A1 BCMDRD_CONFIG_INCLUDE_BCM56963_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963_Bx
#define BCMDRD_CONFIG_INCLUDE_BCM56963_Bx BCMDRD_CONFIG_INCLUDE_BCM56963
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963_B0
#define BCMDRD_CONFIG_INCLUDE_BCM56963_B0 BCMDRD_CONFIG_INCLUDE_BCM56963_Bx
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56963_B1
#define BCMDRD_CONFIG_INCLUDE_BCM56963_B1 BCMDRD_CONFIG_INCLUDE_BCM56963_Bx
#endif
/* Resolve all interchip dependencies */
#if BCMDRD_CONFIG_INCLUDE_BCM56963_A0 == 1
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56963_A1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56963_B0 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56963_B1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif


/*
 * BCM56968
 */

/* Sets the default include state if it was not given */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968
#define BCMDRD_CONFIG_INCLUDE_BCM56968 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
/* Resolve revision dependencies */
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968_Ax
#define BCMDRD_CONFIG_INCLUDE_BCM56968_Ax BCMDRD_CONFIG_INCLUDE_BCM56968
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56968_A0 BCMDRD_CONFIG_INCLUDE_BCM56968_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968_A1
#define BCMDRD_CONFIG_INCLUDE_BCM56968_A1 BCMDRD_CONFIG_INCLUDE_BCM56968_Ax
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968_Bx
#define BCMDRD_CONFIG_INCLUDE_BCM56968_Bx BCMDRD_CONFIG_INCLUDE_BCM56968
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968_B0
#define BCMDRD_CONFIG_INCLUDE_BCM56968_B0 BCMDRD_CONFIG_INCLUDE_BCM56968_Bx
#endif
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56968_B1
#define BCMDRD_CONFIG_INCLUDE_BCM56968_B1 BCMDRD_CONFIG_INCLUDE_BCM56968_Bx
#endif
/* Resolve all interchip dependencies */
#if BCMDRD_CONFIG_INCLUDE_BCM56968_A0 == 1
#ifndef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 BCMDRD_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56968_A1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56968_B0 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM56968_B1 == 1
#if BCMDRD_CONFIG_INCLUDE_BCM56960_A0 != 1
#undef BCMDRD_CONFIG_INCLUDE_BCM56960_A0
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0 1
#define BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED 1
#endif
#endif


#endif /* BCMDRD_CONFIG_CHIPS_H */

/*
 * CONFIG_OPTION Macros. Can be used to determine the build configuration.
 */

#ifdef CONFIG_OPTION
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_Ax)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_A0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_A1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_Bx)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_B0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_B1)
#ifdef BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56960_A0_IMPLIED)
#endif
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961_Ax)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961_A0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961_A1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961_Bx)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961_B0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56961_B1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962_Ax)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962_A0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962_A1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962_Bx)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962_B0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56962_B1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963_Ax)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963_A0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963_A1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963_Bx)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963_B0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56963_B1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968_Ax)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968_A0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968_A1)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968_Bx)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968_B0)
CONFIG_OPTION(BCMDRD_CONFIG_INCLUDE_BCM56968_B1)
#undef CONFIG_OPTION
#endif /* #ifdef CONFIG_OPTION */
