/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from INTERNAL/fltg/xgs/fp/FP_CONFIG.tbl.ltl
 * Edits to this file will be lost when it is regenerated.
 *
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 */
#include <bcmltd/bcmltd_internal.h>
#include <bcmltd/chip/bcmltd_common_enumpool.h>
#include "bcmltd_strpool.h"
static const bcmltd_field_rep_t bcmltd_fp_config_t_fields[] = {
    {
        .name  = bcmltd_strpool_fp_ing_opermode,  /* FP_ING_OPERMODE */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .num_sym = 3,
        .sym = bcmltd_common_fp_ing_opermode_t_enum,
        .desc = "The operating mode of Ingress FP stage.\n The default Value is set to 0 means Global operating mode.\n This field can be set to any of the three MODES as below during\n system initialization to use Ingress FP stage to\n operate in that particular mode. This field cannot be modified during\n run runtime.\n\n      GLOBAL: Global operating mode with no INPORTS qualifier support\n      GLOBAL_PIPE_AWARE: Global Pipe Aware operating mode with INPORTS\n        qualifier support.\n      PIPE_UNIQUE: Pipe Unique operating mode\n",
    },
    {
        .name  = bcmltd_strpool_fp_em_opermode_pipeunique,  /* FP_EM_OPERMODE_PIPEUNIQUE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "The operating mode of Exact Match FP stage. The default Value\n is set to FALSE means Global operating mode. This field\n can be set to TRUE during system initialization to use\n Exact Match FP stage in pipe unique operating mode. This\n field cannot be modified during runtime.\n",
    },
    {
        .name  = bcmltd_strpool_fp_vlan_opermode_pipeunique,  /* FP_VLAN_OPERMODE_PIPEUNIQUE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "The operating mode of Vlan FP stage. The default Value\n is set to FALSE means Global operating mode. This field\n can be set to TRUE during system initialization to use\n Vlan FP stage in pipe unique operating mode. This\n field cannot be modified during runtime.\n",
    },
    {
        .name  = bcmltd_strpool_fp_egr_opermode_pipeunique,  /* FP_EGR_OPERMODE_PIPEUNIQUE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "The operating mode of Egress FP stage. The default Value\n is set to FALSE means Global operating mode. This field\n can be set to TRUE during system initialization to use\n Egress FP stage in pipe unique operating mode. This\n field cannot be modified during runtime.\n",
    },
    {
        .name  = bcmltd_strpool_fp_compression_opermode_pipeunique,  /* FP_COMPRESSION_OPERMODE_PIPEUNIQUE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "The operating mode of FP Compression qualifiers. The default Value\n is set to FALSE means Global operating mode. This field\n can be set to TRUE during system initialization to use\n FP Compression qualifier in pipe unique operating mode. This\n field cannot be modified during runtime.\n",
    },
    {
        .name  = bcmltd_strpool_fp_ing_range_check_opermode_pipeunique,  /* FP_ING_RANGE_CHECK_OPERMODE_PIPEUNIQUE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "The operating mode of FP Range Check qualifier. The default Value\n is set to FALSE means Global operating mode. This field\n can be set to TRUE during system initialization to use\n FP Range Check qualifier in pipe unique operating mode. This\n field cannot be modified during runtime.\n",
    },
};
const bcmltd_table_rep_t bcmltd_fp_config_t = {
    .name = bcmltd_strpool_fp_config, /* FP_CONFIG */
    .flags = BCMLTD_TABLE_F_CONFIG,
    .fields = 6,
    .field = bcmltd_fp_config_t_fields,
    .desc = "This Logical table shows the chip Level configuration parameters\n for different FP engines.\n",
};
