/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from INTERNAL/fltg/xgs/fp/FP_ING_POLICY_TEMPLATE.tbl.ltl
 * Edits to this file will be lost when it is regenerated.
 *
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 */
#include <bcmltd/bcmltd_internal.h>
#include "bcmltd_strpool.h"
static const bcmltd_field_rep_t bcmltd_fp_ing_policy_template_t_fields[] = {
    {
        .name  = bcmltd_strpool_fp_ing_policy_template_id,  /* FP_ING_POLICY_TEMPLATE_ID */
        .flags = BCMLTD_FIELD_F_KEY,
        .width = 32,
        .depth = 0,
        .desc = "Ingress FP Policy Identifier.",
    },
    {
        .name  = bcmltd_strpool_action_r_drop,  /* ACTION_R_DROP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Drop Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_drop,  /* ACTION_Y_DROP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Drop Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_drop,  /* ACTION_G_DROP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Drop Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_untag_pkt_priority,  /* ACTION_NEW_UNTAG_PKT_PRIORITY */
        .flags = 0,
        .width = 3,
        .depth = 0,
        .desc = "Change packets Input Priority.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_color,  /* ACTION_NEW_R_COLOR */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Change Packet Color for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_y_color,  /* ACTION_NEW_Y_COLOR */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Change Packet Color for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_g_color,  /* ACTION_NEW_G_COLOR */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Change Packet Color for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_cos_map,  /* ACTION_NEW_R_COS_MAP */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Unicast COS and Multicast COS using IFP_COS_MAP table\n for Red Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_r_cosq,  /* ACTION_NEW_R_COSQ */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change CosQ of Red Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_r_intpri_to_inner_dot1p,  /* ACTION_R_INTPRI_TO_INNER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal Priority to packets Inner Vlan Tag dot1p priority\n for Red Packet\n",
    },
    {
        .name  = bcmltd_strpool_action_new_r_intpri,  /* ACTION_NEW_R_INTPRI */
        .flags = 0,
        .width = 4,
        .depth = 0,
        .desc = "Change internal priority to a new value for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_r_intpri_to_tos,  /* ACTION_R_INTPRI_TO_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal priority to MSB 3 bits from IP Header\n TOS field for Red Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_r_intpri_updates_cancel,  /* ACTION_R_INTPRI_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change to internal priority cancel for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_uc_cos,  /* ACTION_NEW_R_UC_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Unicast COS for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_mc_cos,  /* ACTION_NEW_R_MC_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Multicast COS for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_y_cos_map,  /* ACTION_NEW_Y_COS_MAP */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Unicast COS and Multicast COS using IFP_COS_MAP table\n for Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_y_cosq,  /* ACTION_NEW_Y_COSQ */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change CosQ of Yellow Packets.\n",
    },
    {
        .name  = bcmltd_strpool_action_y_intpri_to_inner_dot1p,  /* ACTION_Y_INTPRI_TO_INNER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal Priority to packets Inner Vlan Tag dot1p priority\n for Yellow Packet\n",
    },
    {
        .name  = bcmltd_strpool_action_new_y_intpri,  /* ACTION_NEW_Y_INTPRI */
        .flags = 0,
        .width = 4,
        .depth = 0,
        .desc = "Change internal priority to a new value for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_intpri_to_tos,  /* ACTION_Y_INTPRI_TO_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal priority to MSB 3 bits from IP Header\n TOS field for Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_y_intpri_updates_cancel,  /* ACTION_Y_INTPRI_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal priority to a new value for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_y_uc_cos,  /* ACTION_NEW_Y_UC_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Unicast COS for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_y_mc_cos,  /* ACTION_NEW_Y_MC_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Multicast COS for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_g_cos_map,  /* ACTION_NEW_G_COS_MAP */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Unicast COS and Multicast COS using IFP_COS_MAP table\n for Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_g_cosq,  /* ACTION_NEW_G_COSQ */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change CosQ of Green Packets.\n",
    },
    {
        .name  = bcmltd_strpool_action_g_intpri_to_inner_dot1p,  /* ACTION_G_INTPRI_TO_INNER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal Priority to packets Inner Vlan Tag dot1p priority\n for Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_g_intpri,  /* ACTION_NEW_G_INTPRI */
        .flags = 0,
        .width = 4,
        .depth = 0,
        .desc = "Change internal priority to a new value for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_intpri_to_tos,  /* ACTION_G_INTPRI_TO_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal priority to MSB 3 bits from IP Header\n TOS field for Green Packet\n",
    },
    {
        .name  = bcmltd_strpool_action_g_intpri_updates_cancel,  /* ACTION_G_INTPRI_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change internal priority to a new value for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_g_uc_cos,  /* ACTION_NEW_G_UC_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Unicast COS for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_g_mc_cos,  /* ACTION_NEW_G_MC_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Multicast COS for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_mirror_instance_cnt,  /* ACTION_MIRROR_INSTANCE_CNT */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Number of active MTP instance.",
    },
    {
        .name  = bcmltd_strpool_action_mirror_instance_id,  /* ACTION_MIRROR_INSTANCE_ID */
        .flags = 0,
        .width = 8,
        .depth = 4,
        .desc = "Array of MTP instances.",
    },
    {
        .name  = bcmltd_strpool_action_hgt_spray_hash_cancel,  /* ACTION_HGT_SPRAY_HASH_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Disable Spray Hash on HiGiG Ports Trunk.",
    },
    {
        .name  = bcmltd_strpool_action_trunk_spary_hash_cancel,  /* ACTION_TRUNK_SPARY_HASH_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Disable Spray Hash on Front Panel Ports Trunk.",
    },
    {
        .name  = bcmltd_strpool_action_ecmp_spray_hash_cancel,  /* ACTION_ECMP_SPRAY_HASH_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Disable Spray Hash on ECMP Group.",
    },
    {
        .name  = bcmltd_strpool_action_do_not_nat,  /* ACTION_DO_NOT_NAT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Do not NAT.",
    },
    {
        .name  = bcmltd_strpool_action_match_id,  /* ACTION_MATCH_ID */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Set the match ID to packets copied to CPU. This action\n is applied only if COPY_TO_CPU action is present in\n the same POLICY_TEMPLATE  entry.\n",
    },
    {
        .name  = bcmltd_strpool_action_r_copy_to_cpu,  /* ACTION_R_COPY_TO_CPU */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy Yellow Packet to Cpu.",
    },
    {
        .name  = bcmltd_strpool_action_r_copy_to_cpu_cancel,  /* ACTION_R_COPY_TO_CPU_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel Copy Red packet to cpu action set\n by the lower priority rule for Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_r_switch_to_cpu_cancel,  /* ACTION_R_SWITCH_TO_CPU_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Switch to CPU cancel -- Cancel the signal set\n by ingress pipeline to switch the packet to cpu\n for Red Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_r_switch_to_cpu_reinsate,  /* ACTION_R_SWITCH_TO_CPU_REINSATE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "DO NOT Cancel Switch to Cpu - To cancel the 'Cancel\n Switch to CPU' action set by the lower priority rule\n for Red Packet\n",
    },
    {
        .name  = bcmltd_strpool_action_r_copy_to_cpu_with_timestamp,  /* ACTION_R_COPY_TO_CPU_WITH_TIMESTAMP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy packet to CPU with time stamp for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_copy_to_cpu,  /* ACTION_Y_COPY_TO_CPU */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy Yellow Packet to Cpu.",
    },
    {
        .name  = bcmltd_strpool_action_y_copy_to_cpu_cancel,  /* ACTION_Y_COPY_TO_CPU_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel Copy Green packet to cpu action set\n by the lower priority rule for Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_y_switch_to_cpu_cancel,  /* ACTION_Y_SWITCH_TO_CPU_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Switch to CPU cancel - Cancel the signal set\n by ingress pipeline to switch the packet to cpu\n for Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_y_switch_to_cpu_reinsate,  /* ACTION_Y_SWITCH_TO_CPU_REINSATE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "DO NOT Cancel Switch to Cpu - To cancel the 'Cancel\n Switch to CPU' action set by the lower priority rule\n for Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_y_copy_to_cpu_with_timestamp,  /* ACTION_Y_COPY_TO_CPU_WITH_TIMESTAMP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy packet to CPU with time stamp for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_copy_to_cpu,  /* ACTION_G_COPY_TO_CPU */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy Green Packet to Cpu .",
    },
    {
        .name  = bcmltd_strpool_action_g_copy_to_cpu_cancel,  /* ACTION_G_COPY_TO_CPU_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel Copy Green packet to cpu action set\n by the lower priority rule for Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_g_switch_to_cpu_cancel,  /* ACTION_G_SWITCH_TO_CPU_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Switch to CPU cancel - Cancel the signal set\n by ingress pipeline to switch the packet to cpu\n for Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_g_switch_to_cpu_reinsate,  /* ACTION_G_SWITCH_TO_CPU_REINSATE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "DO NOT Cancel Switch to Cpu - To cancel the 'Cancel\n Switch to CPU' action set by the lower priority rule\n for Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_g_copy_to_cpu_with_timestamp,  /* ACTION_G_COPY_TO_CPU_WITH_TIMESTAMP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy packet to CPU with time stamp for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_do_not_cut_through,  /* ACTION_DO_NOT_CUT_THROUGH */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "DO NOT cut-through the packet if ingress pipeline\n set the packet to cutthrough.\n",
    },
    {
        .name  = bcmltd_strpool_action_do_not_urpf,  /* ACTION_DO_NOT_URPF */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "DO NOT URPF if the ingress pipilne set the packet to URPF.",
    },
    {
        .name  = bcmltd_strpool_action_do_not_change_ttl,  /* ACTION_DO_NOT_CHANGE_TTL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Do NOT change Packet TTL.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_ecn,  /* ACTION_NEW_R_ECN */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change ECN for Red packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_y_ecn,  /* ACTION_NEW_Y_ECN */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change ECN for Yellow packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_g_ecn,  /* ACTION_NEW_G_ECN */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change ECN for Green packet.",
    },
    {
        .name  = bcmltd_strpool_action_r_preserve_dot1p,  /* ACTION_R_PRESERVE_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Preserve packets dot1p value for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_r_outer_dot1p_to_inner_dot1p,  /* ACTION_R_OUTER_DOT1P_TO_INNER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy Inner Vlan Tags dot1p value to outer Vlan Tag for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_outer_dot1p,  /* ACTION_NEW_R_OUTER_DOT1P */
        .flags = 0,
        .width = 3,
        .depth = 0,
        .desc = "Change Outer Vlan Tags dot1p bits to new value for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_r_outer_dot1p_to_tos,  /* ACTION_R_OUTER_DOT1P_TO_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change Outer Vlan Tag dot1p Value to bit(7,5) of TOS\n for Red Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_r_dot1p_updates_cancel,  /* ACTION_R_DOT1P_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Do not change packet dot1p value for Red Packet\n This overrides dot1p actions from lower priority logical\n tables, but does not result in an action out of the IFP\n",
    },
    {
        .name  = bcmltd_strpool_action_y_preserve_dot1p,  /* ACTION_Y_PRESERVE_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Preserve packets dot1p value for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_outer_dot1p_to_inner_dot1p,  /* ACTION_Y_OUTER_DOT1P_TO_INNER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy Inner Vlan Tags dot1p value to outer Vlan Tag for\n Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_y_outer_dot1p,  /* ACTION_NEW_Y_OUTER_DOT1P */
        .flags = 0,
        .width = 3,
        .depth = 0,
        .desc = "Change Outer Vlan Tags dot1p bits to new value for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_outer_dot1p_to_tos,  /* ACTION_Y_OUTER_DOT1P_TO_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change Outer Vlan Tag dot1p value to TOS (bit [7,5]) for\n Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_y_dot1p_updates_cancel,  /* ACTION_Y_DOT1P_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Do not change packet dot1p value for Yellow Packet\n This overrides dot1p actions from lower priority logical\n tables, but does not result in an action out of the IFP\n",
    },
    {
        .name  = bcmltd_strpool_action_g_preserve_dot1p,  /* ACTION_G_PRESERVE_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Preserve packets dot1p value for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_outer_dot1p_to_inner_dot1p,  /* ACTION_G_OUTER_DOT1P_TO_INNER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Copy Inner Vlan Tag dot1p value to outer Vlan Tag for\n Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_g_outer_dot1p,  /* ACTION_NEW_G_OUTER_DOT1P */
        .flags = 0,
        .width = 3,
        .depth = 0,
        .desc = "Change Outer Vlan Tags dot1p bits to new value for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_outer_dot1p_to_tos,  /* ACTION_G_OUTER_DOT1P_TO_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change Outer Vlan Tag dot1p value to TOS (bit [7,5]) for\n Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_g_dot1p_updates_cancel,  /* ACTION_G_DOT1P_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Do not change packet dot1p value for Yellow Packet\n This overrides dot1p actions from lower priority logical\n tables, but does not result in an action out of the IFP\n",
    },
    {
        .name  = bcmltd_strpool_action_new_r_dscp,  /* ACTION_NEW_R_DSCP */
        .flags = 0,
        .width = 6,
        .depth = 0,
        .desc = "Change DSCP to a new value for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_r_dscp_updates_cancel,  /* ACTION_R_DSCP_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "This action overrides CHANGE_DSCP actions from lower priority\n logical tables for Red Packet, but does not result in an action\n out of the IFP\n",
    },
    {
        .name  = bcmltd_strpool_action_r_preserve_dscp,  /* ACTION_R_PRESERVE_DSCP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Sets the PRESERVE_DSCP indication in the HiGig header for\n Red Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_y_dscp,  /* ACTION_NEW_Y_DSCP */
        .flags = 0,
        .width = 6,
        .depth = 0,
        .desc = "Change DSCP to a new value for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_dscp_updates_cancel,  /* ACTION_Y_DSCP_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "This action overrides CHANGE_DSCP actions from lower priority\n logical tables for Yellow Packet, but does not result in an action\n out of the IFP\n",
    },
    {
        .name  = bcmltd_strpool_action_y_preserve_dscp,  /* ACTION_Y_PRESERVE_DSCP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Sets the PRESERVE_DSCP indication in the HiGig header for\n Yellow Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_g_dscp,  /* ACTION_NEW_G_DSCP */
        .flags = 0,
        .width = 6,
        .depth = 0,
        .desc = "Change DSCP to a new value for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_dscp_updates_cancel,  /* ACTION_G_DSCP_UPDATES_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "This action overrides CHANGE_DSCP actions from lower priority\n logical tables for Green Packet, but does not result in an action\n out of the IFP\n",
    },
    {
        .name  = bcmltd_strpool_action_g_preserve_dscp,  /* ACTION_G_PRESERVE_DSCP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Sets the PRESERVE_DSCP indication in the HiGig header for\n Green Packet.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_g_tos,  /* ACTION_NEW_G_TOS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change bits (7,5) of TOS to a new value for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_tos_to_pre_fp_ing_outer_dot1p,  /* ACTION_G_TOS_TO_PRE_FP_ING_OUTER_DOT1P */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Change bits (7,5) of TOS to the dot1p value\n from the pre-IFP Outer VLAN Tag for Green Packets\n",
    },
    {
        .name  = bcmltd_strpool_action_change_pkt_l2_fields,  /* ACTION_CHANGE_PKT_L2_FIELDS */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Change different L2 Fields in the packet with new values.\n New values comes from EGR_L3_NEXT_HOP (view type: IFP_ACTIONS)\n L2 Fields that can be modified using this action:\n Source MAC Address\n Destination MAC Address\n Outer Vlan\n VnTag (Modify\n Etag (Modify\n",
    },
    {
        .name  = bcmltd_strpool_action_change_pkt_l2_fields_cancel,  /* ACTION_CHANGE_PKT_L2_FIELDS_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Dont Change L2 fieldsin the packet. It cancels Action from\n CHANGE_PKT_L2_FIELDS set by the lower priority rule\n",
    },
    {
        .name  = bcmltd_strpool_action_new_classification_tag,  /* ACTION_NEW_CLASSIFICATION_TAG */
        .flags = 0,
        .width = 32,
        .depth = 0,
        .desc = "Add Classification Tag.",
    },
    {
        .name  = bcmltd_strpool_action_switch_to_l3uc,  /* ACTION_SWITCH_TO_L3UC */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Switch the packet to L3 Unicast Destination.",
    },
    {
        .name  = bcmltd_strpool_action_switch_to_ecmp,  /* ACTION_SWITCH_TO_ECMP */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Switch the packet to ECMP Group.",
    },
    {
        .name  = bcmltd_strpool_action_l3_switch_cancel,  /* ACTION_L3_SWITCH_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel L3 Switch action set by the lower priority rule.",
    },
    {
        .name  = bcmltd_strpool_action_i2e_classid_select,  /* ACTION_I2E_CLASSID_SELECT */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Select I2E class Id.",
    },
    {
        .name  = bcmltd_strpool_action_higig_classid_select,  /* ACTION_HIGIG_CLASSID_SELECT */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Select HiGig Class Id.",
    },
    {
        .name  = bcmltd_strpool_action_new_i2e_classid,  /* ACTION_NEW_I2E_CLASSID */
        .flags = 0,
        .width = 12,
        .depth = 0,
        .desc = "Assign a new class Id to pass to Egress pipeline.",
    },
    {
        .name  = bcmltd_strpool_action_new_bfd_seession_idx,  /* ACTION_NEW_BFD_SEESSION_IDX */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Assign new BFD Session Index.",
    },
    {
        .name  = bcmltd_strpool_action_new_cpu_cos,  /* ACTION_NEW_CPU_COS */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Set new Cos to packets copied to or switched to CPU\n This Action is conflicting with NEW_SERVICE_POOL_ID\n Only one can be set at a time\n",
    },
    {
        .name  = bcmltd_strpool_action_new_service_pool_id,  /* ACTION_NEW_SERVICE_POOL_ID */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "This Action is conflicting with NEW_CPU_COS\n Only one can be set at a time\n",
    },
    {
        .name  = bcmltd_strpool_action_r_drop_cancel,  /* ACTION_R_DROP_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel the Drop set by the lower priority rule for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_y_drop_cancel,  /* ACTION_Y_DROP_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel the Drop set by the lower priority rule for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_g_drop_cancel,  /* ACTION_G_DROP_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Cancel the Drop set by the lower priority rule for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_g_intcn,  /* ACTION_NEW_G_INTCN */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Internal Congestion for Green Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_y_intcn,  /* ACTION_NEW_Y_INTCN */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Internal Congestion for Yellow Packet.",
    },
    {
        .name  = bcmltd_strpool_action_new_r_intcn,  /* ACTION_NEW_R_INTCN */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Change Internal Congestion for Red Packet.",
    },
    {
        .name  = bcmltd_strpool_action_mirror_override,  /* ACTION_MIRROR_OVERRIDE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Override the Mirror. This field generates a single Mirror\n Override action out of the physical slice. This action is\n used to cancel all mirror copies of the packet (IFP-generated\n mirror copies and switch-logic generated mirror copies)\n",
    },
    {
        .name  = bcmltd_strpool_action_sflow_enable,  /* ACTION_SFLOW_ENABLE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable SFLOW on packet.",
    },
    {
        .name  = bcmltd_strpool_action_enable_pkt_visibility,  /* ACTION_ENABLE_PKT_VISIBILITY */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable Instrumentation. This action will trigger storing\n all instrumentation triggers for this packet to a buffer\n",
    },
    {
        .name  = bcmltd_strpool_action_redirect_to_module,  /* ACTION_REDIRECT_TO_MODULE */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Redirect to Module and do switch logic forwarding\n modifications\n",
    },
    {
        .name  = bcmltd_strpool_action_redirect_to_port,  /* ACTION_REDIRECT_TO_PORT */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Redirect to System Physical Port and do switch logic forwarding\n modifications\n",
    },
    {
        .name  = bcmltd_strpool_action_redirect_to_dvp,  /* ACTION_REDIRECT_TO_DVP */
        .flags = 0,
        .width = 32,
        .depth = 0,
        .desc = "Redirect to DVP.",
    },
    {
        .name  = bcmltd_strpool_action_redirect_to_trunk,  /* ACTION_REDIRECT_TO_TRUNK */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Redirect to Trunk and do switch logic forwarding modifications.",
    },
    {
        .name  = bcmltd_strpool_action_unmodified_redirect_to_module,  /* ACTION_UNMODIFIED_REDIRECT_TO_MODULE */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Redirect to Module but do not perform switch logic forwarding\n Modifications\n",
    },
    {
        .name  = bcmltd_strpool_action_unmodified_redirect_to_trunk,  /* ACTION_UNMODIFIED_REDIRECT_TO_TRUNK */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Redirect to Trunk but do not perform switch logic forwarding\n modifications\n",
    },
    {
        .name  = bcmltd_strpool_action_unmodified_redirect_to_port,  /* ACTION_UNMODIFIED_REDIRECT_TO_PORT */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Redirect to System Physical Port and do not perform switch logic\n forwarding modifications\n",
    },
    {
        .name  = bcmltd_strpool_action_redirect_to_nhop,  /* ACTION_REDIRECT_TO_NHOP */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Redirect to Next Hop.",
    },
    {
        .name  = bcmltd_strpool_action_redirect_to_ecmp,  /* ACTION_REDIRECT_TO_ECMP */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Redirect to ECMP Group.",
    },
    {
        .name  = bcmltd_strpool_action_redirect_uc_cancel,  /* ACTION_REDIRECT_UC_CANCEL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "DO NOT Redirect to Unicast Destination.\n Cancels all Unicast redirect actions set by the lower prioirty rule.\n",
    },
    {
        .name  = bcmltd_strpool_action_new_higig_eh,  /* ACTION_NEW_HIGIG_EH */
        .flags = 0,
        .width = 32,
        .depth = 0,
        .desc = "Add HiGiG Extended Header.",
    },
    {
        .name  = bcmltd_strpool_action_higig_eh_mask_profile_id,  /* ACTION_HIGIG_EH_MASK_PROFILE_ID */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "HiGig Extended header Profile Id.",
    },
    {
        .name  = bcmltd_strpool_action_nat_egr_override,  /* ACTION_NAT_EGR_OVERRIDE */
        .flags = 0,
        .width = 16,
        .depth = 0,
        .desc = "Override Egress NAT.",
    },
};
const bcmltd_table_rep_t bcmltd_fp_ing_policy_template_t = {
    .name = bcmltd_strpool_fp_ing_policy_template, /* FP_ING_POLICY_TEMPLATE */
    .flags = 0,
    .fields = 120,
    .field = bcmltd_fp_ing_policy_template_t_fields,
    .desc = "",
};
