/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from INTERNAL/fltg/xgs/pc/PC_AUTONEG_PROFILE.tbl.ltl
 * Edits to this file will be lost when it is regenerated.
 *
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 */
#include <bcmltd/bcmltd_internal.h>
#include "bcmltd_strpool.h"
static const bcmltd_field_rep_t bcmltd_pc_autoneg_profile_t_fields[] = {
    {
        .name  = bcmltd_strpool_pc_autoneg_profile_id,  /* PC_AUTONEG_PROFILE_ID */
        .flags = BCMLTD_FIELD_F_KEY,
        .width = 16,
        .depth = 0,
        .desc = "Auto-negotiation profile ID.",
    },
    {
        .name  = bcmltd_strpool_an_parallel_detect,  /* AN_PARALLEL_DETECT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Parallel detection (no exchange of information).",
    },
    {
        .name  = bcmltd_strpool_an_cl28,  /* AN_CL28 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable IEEE 802.3 clause 28 auto-negotiation.",
    },
    {
        .name  = bcmltd_strpool_an_cl37,  /* AN_CL37 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable IEEE 802.3 clause 37 auto-negotiation.",
    },
    {
        .name  = bcmltd_strpool_an_cl73,  /* AN_CL73 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable IEEE 802.3 clause 73 auto-negotiation.",
    },
    {
        .name  = bcmltd_strpool_an_sgmii,  /* AN_SGMII */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable SGMII auto-negotiation.",
    },
    {
        .name  = bcmltd_strpool_an_bam37,  /* AN_BAM37 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable Broadcom clause 37 auto-negotiation.",
    },
    {
        .name  = bcmltd_strpool_an_bam73,  /* AN_BAM73 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Enable Broadcom clause 73 auto-negotiation.",
    },
    {
        .name  = bcmltd_strpool_adv_10m_t,  /* ADV_10M_T */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Mbps copper mode (10BASE-T).",
    },
    {
        .name  = bcmltd_strpool_adv_10m_t_hdx,  /* ADV_10M_T_HDX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Mbps copper half-duplex mode (10BASE-T HDX).",
    },
    {
        .name  = bcmltd_strpool_adv_100m_t,  /* ADV_100M_T */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 100 Mbps copper mode (100BASE-T).",
    },
    {
        .name  = bcmltd_strpool_adv_100m_t_hdx,  /* ADV_100M_T_HDX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 100 Mbps copper half-duplex mode (100BASE-T HDX).",
    },
    {
        .name  = bcmltd_strpool_adv_100m_fx,  /* ADV_100M_FX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 100 Mbps fiber mode (100BASE-FX).",
    },
    {
        .name  = bcmltd_strpool_adv_1000m_t,  /* ADV_1000M_T */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 1000 Mbps copper mode (1000BASE-T).",
    },
    {
        .name  = bcmltd_strpool_adv_1000m_x,  /* ADV_1000M_X */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 1000 Mbps fiber mode (1000BASE-X).",
    },
    {
        .name  = bcmltd_strpool_adv_2p5g,  /* ADV_2P5G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 2.5 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_10g,  /* ADV_10G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Gbps XAUI mode.",
    },
    {
        .name  = bcmltd_strpool_adv_10g_cx,  /* ADV_10G_CX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Gbps CX mode (10GBASE-CX4).",
    },
    {
        .name  = bcmltd_strpool_adv_10g_cr,  /* ADV_10G_CR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Gbps CR mode (10GBASE-CR2/CR4).",
    },
    {
        .name  = bcmltd_strpool_adv_10g_kr,  /* ADV_10G_KR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Gbps KR mode (10GBASE-KR/KR2).",
    },
    {
        .name  = bcmltd_strpool_adv_10g_kx,  /* ADV_10G_KX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 10 Gbps KX mode (10GBASE-KX4).",
    },
    {
        .name  = bcmltd_strpool_adv_12g,  /* ADV_12G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 12 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_13g,  /* ADV_13G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 13 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_20g,  /* ADV_20G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 20 Gbps XAUI/RXAUI mode.",
    },
    {
        .name  = bcmltd_strpool_adv_20g_cx,  /* ADV_20G_CX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 20 Gbps CX mode (20GBASE-CX4).",
    },
    {
        .name  = bcmltd_strpool_adv_20g_cr,  /* ADV_20G_CR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 20 Gbps CR mode (20GBASE-CR2/CR4).",
    },
    {
        .name  = bcmltd_strpool_adv_20g_kr,  /* ADV_20G_KR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 20 Gbps KR mode (20GBASE-KR2).",
    },
    {
        .name  = bcmltd_strpool_adv_21g,  /* ADV_21G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 21 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_40g,  /* ADV_40G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 40 Gbps XLAUI mode.",
    },
    {
        .name  = bcmltd_strpool_adv_40g_cr,  /* ADV_40G_CR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 40 Gbps CR mode (40GBASE-CR4).",
    },
    {
        .name  = bcmltd_strpool_adv_40g_kr,  /* ADV_40G_KR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 40 Gbps KR mode (40GBASE-KR4).",
    },
    {
        .name  = bcmltd_strpool_adv_42g,  /* ADV_42G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 42 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_100g,  /* ADV_100G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 100 Gbps CAUI mode.",
    },
    {
        .name  = bcmltd_strpool_adv_100g_cr,  /* ADV_100G_CR */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 100 Gbps CR mode (100GBASE-CR4/CR10).",
    },
    {
        .name  = bcmltd_strpool_adv_120g,  /* ADV_120G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 120 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_127g,  /* ADV_127G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 127 Gbps mode (HiGig only).",
    },
    {
        .name  = bcmltd_strpool_adv_pause_tx,  /* ADV_PAUSE_TX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise asymmetric Tx PAUSE (symmetric if ADV_PAUSE_RX=1).",
    },
    {
        .name  = bcmltd_strpool_adv_pause_rx,  /* ADV_PAUSE_RX */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise symmetric if ADV_PAUSE_TX=1.",
    },
    {
        .name  = bcmltd_strpool_adv_eee_100m,  /* ADV_EEE_100M */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 100 Mbps Energy Efficient Ethernet support.",
    },
    {
        .name  = bcmltd_strpool_adv_eee_1g,  /* ADV_EEE_1G */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Advertise 1000 Mbps Energy Efficient Ethernet support.",
    },
};
const bcmltd_table_rep_t bcmltd_pc_autoneg_profile_t = {
    .name = bcmltd_strpool_pc_autoneg_profile, /* PC_AUTONEG_PROFILE */
    .flags = 0,
    .fields = 40,
    .field = bcmltd_pc_autoneg_profile_t_fields,
    .desc = "Auto-negotiation profile.\n\n This table provides a simple way to share auto-negotiation settings\n across multiple ports of the same type. Furthermore it serves the\n purpose of keeping the PC_PORT table more manageable.\n\n The table has three main sections of which the first one describes\n the supported auto-negotiation methods, the second one describes the\n advertised port operating modes, and the third one describes the\n advertised MAC abilities (PAUSE and EEE).\n",
};
