/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from INTERNAL/fltg/xgs/fp/FP_VLAN_GRP_TEMPLATE.tbl.ltl
 * Edits to this file will be lost when it is regenerated.
 *
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 */
#include <bcmltd/bcmltd_internal.h>
#include "bcmltd_strpool.h"
static const bcmltd_field_rep_t bcmltd_fp_vlan_grp_template_t_fields[] = {
    {
        .name  = bcmltd_strpool_fp_vlan_grp_template_id,  /* FP_VLAN_GRP_TEMPLATE_ID */
        .flags = BCMLTD_FIELD_F_KEY,
        .width = 16,
        .depth = 0,
        .desc = "Vlan FP Group Identifier.",
    },
    {
        .name  = bcmltd_strpool_mode_oper,  /* MODE_OPER */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Operational Group Mode(Read Only) of the group.\n If MODE_AUTO is set, then MODE_OPER field will updated with mode\n assigned to group by SDK.\n If MODE_AUTO is not set and  if group fits in mode specified in\n MODE field, then MODE field will be assigned to MODE_OPER field.\n",
    },
    {
        .name  = bcmltd_strpool_pipe,  /* PIPE */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "XGS Pipeline Number.",
    },
    {
        .name  = bcmltd_strpool_entry_priority,  /* ENTRY_PRIORITY */
        .flags = 0,
        .width = 32,
        .depth = 0,
        .desc = "Group Priority. Groups with same priority will share the same\n physical resources(VFP slices) if enough free entries is available to\n accommodate all groups with that priority.\n",
    },
    {
        .name  = bcmltd_strpool_mode_auto,  /* MODE_AUTO */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "When this field is set to TRUE, group mode is calculated through\n internal logic implicitly and the determined mode is reflected in\n MODE_OPER field, group mode specified in MODE field is ignored.\n When this field is set to FALSE, user-specified mode in MODE field\n is used as group mode and MODE_OPER field is updated with this value.\n",
    },
    {
        .name  = bcmltd_strpool_mode,  /* MODE */
        .flags = BCMLTD_FIELD_F_ENUM,
        .width = 32,
        .depth = 0,
        .desc = "Below Enum defines permissible mode that can be configured.\n    SINGLE     : Single Wide mode\n    DBLINTRA   : Double Wide Intra-slice mode\n    DBLINTER   : Double Wide Inter-slice mode\n    QUAD       : Quad Wide mode\n This field is don't care if MODE_AUTO is set to TRUE.\n",
    },
    {
        .name  = bcmltd_strpool_virtual_slice_grp,  /* VIRTUAL_SLICE_GRP */
        .flags = 0,
        .width = 8,
        .depth = 0,
        .desc = "Virtual slice group.\n Field groups created with same virtual slice group\n will be under one virtual group set.\n Policy resolution among groups in a virtual group set\n will result in policy (actions and counter) belonging to\n higher priority group in the virtual group set.\n Policy resolution among different virtual group sets\n will result in combined counter, non-conflicting actions\n from all virtual group sets and for conflicting actions group\n with the highest priority will take precedence across\n all such virtual group sets.\n Allowed values [0 to number of slices-1].\n",
    },
    {
        .name  = bcmltd_strpool_qual_vlan_outer_present,  /* QUAL_VLAN_OUTER_PRESENT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet Outer Vlan Tag Status.",
    },
    {
        .name  = bcmltd_strpool_qual_outer_vlan_id,  /* QUAL_OUTER_VLAN_ID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Outer Vlan Id.",
    },
    {
        .name  = bcmltd_strpool_qual_outer_vlan_cfi,  /* QUAL_OUTER_VLAN_CFI */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Outer Vlan CFI.",
    },
    {
        .name  = bcmltd_strpool_qual_outer_vlan_pri,  /* QUAL_OUTER_VLAN_PRI */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Outer Vlan Priority.",
    },
    {
        .name  = bcmltd_strpool_qual_vlan_inner_present,  /* QUAL_VLAN_INNER_PRESENT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet Inner Vlan Tag Status.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_vlan_id,  /* QUAL_INNER_VLAN_ID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Vlan Id.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_vlan_cfi,  /* QUAL_INNER_VLAN_CFI */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Vlan CFI.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_vlan_pri,  /* QUAL_INNER_VLAN_PRI */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Vlan Priority.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_ip_proto_common,  /* QUAL_INNER_IP_PROTO_COMMON */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner IP Protocol Common field.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_proto_common,  /* QUAL_IP_PROTO_COMMON */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Common IP protocols.",
    },
    {
        .name  = bcmltd_strpool_qual_tunnel_terminated,  /* QUAL_TUNNEL_TERMINATED */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Tunnel terminated traffic.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_checksum_valid,  /* QUAL_IP_CHECKSUM_VALID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet has matching IP Checksum.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_tpid,  /* QUAL_INNER_TPID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner TPID of the Packet.",
    },
    {
        .name  = bcmltd_strpool_qual_outer_tpid,  /* QUAL_OUTER_TPID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Outer TPID of the packet",
    },
    {
        .name  = bcmltd_strpool_qual_l2_format,  /* QUAL_L2_FORMAT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "L2 packet format",
    },
    {
        .name  = bcmltd_strpool_qual_higiglookup_pkt,  /* QUAL_HIGIGLOOKUP_PKT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet is received on HiGiG Port and Table lookup happened.",
    },
    {
        .name  = bcmltd_strpool_qual_higig_pkt,  /* QUAL_HIGIG_PKT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet Received on HiGiG Port.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_ip_type,  /* QUAL_INNER_IP_TYPE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner ip header IP Type.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_type,  /* QUAL_IP_TYPE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "IP Type.",
    },
    {
        .name  = bcmltd_strpool_qual_src_trunk,  /* QUAL_SRC_TRUNK */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "SGLP - Source Trunk Group ID.",
    },
    {
        .name  = bcmltd_strpool_qual_src_vp,  /* QUAL_SRC_VP */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source VP.",
    },
    {
        .name  = bcmltd_strpool_qual_src_port,  /* QUAL_SRC_PORT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source Port.",
    },
    {
        .name  = bcmltd_strpool_qual_src_module,  /* QUAL_SRC_MODULE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source Module.",
    },
    {
        .name  = bcmltd_strpool_qual_inport,  /* QUAL_INPORT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Single Input Port.",
    },
    {
        .name  = bcmltd_strpool_qual_system_port_class,  /* QUAL_SYSTEM_PORT_CLASS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Class Id from SOURCE_TRUNK_MAP.",
    },
    {
        .name  = bcmltd_strpool_qual_l4_pkt,  /* QUAL_L4_PKT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "L4 Packet (has Valid L4 Source and Destination Port).",
    },
    {
        .name  = bcmltd_strpool_qual_inner_ttl,  /* QUAL_INNER_TTL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Packet TTL.",
    },
    {
        .name  = bcmltd_strpool_qual_ttl,  /* QUAL_TTL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet TTL.",
    },
    {
        .name  = bcmltd_strpool_qual_tcp_control_flags,  /* QUAL_TCP_CONTROL_FLAGS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "TCP control flags.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_ip_flags_mf,  /* QUAL_INNER_IP_FLAGS_MF */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Flags in Inner IP Header - More Fragment.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_ip_flags_df,  /* QUAL_INNER_IP_FLAGS_DF */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Flags in Inner IP Header - Dont Fragment.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_flags_mf,  /* QUAL_IP_FLAGS_MF */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Flags in IP Header - More Fragment.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_flags_df,  /* QUAL_IP_FLAGS_DF */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Flags in IP Header - Dont Fragment.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_tos,  /* QUAL_INNER_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Packet TOS.",
    },
    {
        .name  = bcmltd_strpool_qual_tos,  /* QUAL_TOS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Packet TOS.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_l4dst_port,  /* QUAL_INNER_L4DST_PORT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner L4 Header Destination Port.",
    },
    {
        .name  = bcmltd_strpool_qual_l4dst_port,  /* QUAL_L4DST_PORT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "L4 Header Destination Port.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_l4src_port,  /* QUAL_INNER_L4SRC_PORT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner L4 header Source Port.",
    },
    {
        .name  = bcmltd_strpool_qual_l4src_port,  /* QUAL_L4SRC_PORT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "L4 header Source Port.",
    },
    {
        .name  = bcmltd_strpool_qual_icmp_type_code,  /* QUAL_ICMP_TYPE_CODE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "ICMP type code.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_ip_protocol,  /* QUAL_INNER_IP_PROTOCOL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "IP Protocol Field.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_protocol,  /* QUAL_IP_PROTOCOL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "IP protocol.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_dst_ip4,  /* QUAL_INNER_DST_IP4 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Destination IPv4 address.",
    },
    {
        .name  = bcmltd_strpool_qual_dst_ip4,  /* QUAL_DST_IP4 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Destination IPv4 address.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_src_ip4,  /* QUAL_INNER_SRC_IP4 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner Source IPv4 address.",
    },
    {
        .name  = bcmltd_strpool_qual_src_ip4,  /* QUAL_SRC_IP4 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source IPv4 address.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_src_ip6,  /* QUAL_INNER_SRC_IP6 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner ip header source IPv6 address.",
    },
    {
        .name  = bcmltd_strpool_qual_src_ip6,  /* QUAL_SRC_IP6 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source IPv6 Address.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_dst_ip6,  /* QUAL_INNER_DST_IP6 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner ip header destination IPv6 address.",
    },
    {
        .name  = bcmltd_strpool_qual_dst_ip6,  /* QUAL_DST_IP6 */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Destination IPV6 Address.",
    },
    {
        .name  = bcmltd_strpool_qual_ethertype,  /* QUAL_ETHERTYPE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Ethertype.",
    },
    {
        .name  = bcmltd_strpool_qual_src_mac,  /* QUAL_SRC_MAC */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source MAC address.",
    },
    {
        .name  = bcmltd_strpool_qual_dst_mac,  /* QUAL_DST_MAC */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Destination MAC address.",
    },
    {
        .name  = bcmltd_strpool_qual_inner_src_ip6_high,  /* QUAL_INNER_SRC_IP6_HIGH */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner IP header Source IPv6 Address (High/Upper 64 bits).",
    },
    {
        .name  = bcmltd_strpool_qual_src_ip6_high,  /* QUAL_SRC_IP6_HIGH */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Source IPv6 Address (High/Upper 64 bits).",
    },
    {
        .name  = bcmltd_strpool_qual_inner_dst_ip6_high,  /* QUAL_INNER_DST_IP6_HIGH */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Inner IP header Destination IPv6 Address (High/Upper 64 bits).",
    },
    {
        .name  = bcmltd_strpool_qual_dst_ip6_high,  /* QUAL_DST_IP6_HIGH */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Destination IPv6 Address (High/Upper 64 bits).",
    },
    {
        .name  = bcmltd_strpool_qual_vntag,  /* QUAL_VNTAG */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "NIV VN tag (Network Interface Virtualization virtual network tag).",
    },
    {
        .name  = bcmltd_strpool_qual_snap_header,  /* QUAL_SNAP_HEADER */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Sub-Network Attachment Point header (SNAP header).",
    },
    {
        .name  = bcmltd_strpool_qual_llc_header,  /* QUAL_LLC_HEADER */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Logical Link Control Header.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_inner_header_type,  /* QUAL_FIBRE_INNER_HEADER_TYPE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Fibre channel Inner Header Type.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_outer_header_type,  /* QUAL_FIBRE_OUTER_HEADER_TYPE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Fibre channel Outer Header Type.",
    },
    {
        .name  = bcmltd_strpool_qual_fcoe_sof,  /* QUAL_FCOE_SOF */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FCoE Start of Frame.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_data_field_ctrl,  /* QUAL_FIBRE_DATA_FIELD_CTRL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_DATA_FIELD_CTRL.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_class_spec_ctrl,  /* QUAL_FIBRE_CLASS_SPEC_CTRL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_CLASS_SPEC_CTRL.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_frame_ctrl,  /* QUAL_FIBRE_FRAME_CTRL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_FRAME_CTRL.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_type,  /* QUAL_FIBRE_TYPE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_TYPE.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_dst_id,  /* QUAL_FIBRE_DST_ID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_DST_ID.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_src_id,  /* QUAL_FIBRE_SRC_ID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_SRC_ID.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_routing_ctrl,  /* QUAL_FIBRE_ROUTING_CTRL */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "FIBRE_ROUTING_CTRL.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_first_eh_subcode,  /* QUAL_IP_FIRST_EH_SUBCODE */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "First byte after the extension header length field.",
    },
    {
        .name  = bcmltd_strpool_qual_ip_first_eh_proto,  /* QUAL_IP_FIRST_EH_PROTO */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Next header field in first header extension header.",
    },
    {
        .name  = bcmltd_strpool_qual_l3_intf_class,  /* QUAL_L3_INTF_CLASS */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "L3 interface Class ID.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_vft_hop_count,  /* QUAL_FIBRE_VFT_HOP_COUNT */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Fibre Channel's VFT Hop Count.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_vft_vsan_id,  /* QUAL_FIBRE_VFT_VSAN_ID */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Fibre Channel's VFT Internal VSAN ID.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_vft_vsan_pri,  /* QUAL_FIBRE_VFT_VSAN_PRI */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Fibre Channel's VFT VSAN(virtual storage area network) Priority.",
    },
    {
        .name  = bcmltd_strpool_qual_fibre_vft_version,  /* QUAL_FIBRE_VFT_VERSION */
        .flags = 0,
        .width = 1,
        .depth = 0,
        .desc = "Fibre Channel's VFT(Virtual Fabric Tagging) version.",
    },
    {
        .name  = bcmltd_strpool_qual_udf_chunks,  /* QUAL_UDF_CHUNKS */
        .flags = 0,
        .width = 16,
        .depth = 16,
        .desc = "Bitmap for UDF Chunks qualifiers.",
    },
};
const bcmltd_table_rep_t bcmltd_fp_vlan_grp_template_t = {
    .name = bcmltd_strpool_fp_vlan_grp_template, /* FP_VLAN_GRP_TEMPLATE */
    .flags = 0,
    .fields = 85,
    .field = bcmltd_fp_vlan_grp_template_t_fields,
    .desc = "Logical table to create groups in Vlan Field Processor Stage.\n\n Each entry will have Qualifier configuration information,\n virtual slice group number, group priority, pipe instance and\n group mode.\n\n Configures the VFP hardware appropriate for the given elements in a entry.\n\n entry cannot be deleted if rules are created in the group.\n\n Deleting the entry deletes the group.\n\n If no rules are created in the group, all fields in the entry are are\n read-write.\n\n If rules are created in the group, all valid qualifier and action\n configurations, pipe and group mode in the entry are read-only. All invalid\n qualifier and action configurations and priority in the entry are\n read-write.\n",
};
