/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * 
 * Copyright: (c) 2018 Broadcom. All Rights Reserved. "Broadcom" refers to 
 * Broadcom Limited and/or its subsidiaries.
 * 
 * Broadcom Switch Software License
 * 
 * This license governs the use of the accompanying Broadcom software. Your 
 * use of the software indicates your acceptance of the terms and conditions 
 * of this license. If you do not agree to the terms and conditions of this 
 * license, do not use the software.
 * 1. Definitions
 *    "Licensor" means any person or entity that distributes its Work.
 *    "Software" means the original work of authorship made available under 
 *    this license.
 *    "Work" means the Software and any additions to or derivative works of 
 *    the Software that are made available under this license.
 *    The terms "reproduce," "reproduction," "derivative works," and 
 *    "distribution" have the meaning as provided under U.S. copyright law.
 *    Works, including the Software, are "made available" under this license 
 *    by including in or with the Work either (a) a copyright notice 
 *    referencing the applicability of this license to the Work, or (b) a copy 
 *    of this license.
 * 2. Grant of Copyright License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    copyright license to reproduce, prepare derivative works of, publicly 
 *    display, publicly perform, sublicense and distribute its Work and any 
 *    resulting derivative works in any form.
 * 3. Grant of Patent License
 *    Subject to the terms and conditions of this license, each Licensor 
 *    grants to you a perpetual, worldwide, non-exclusive, and royalty-free 
 *    patent license to make, have made, use, offer to sell, sell, import, and 
 *    otherwise transfer its Work, in whole or in part. This patent license 
 *    applies only to the patent claims licensable by Licensor that would be 
 *    infringed by Licensor's Work (or portion thereof) individually and 
 *    excluding any combinations with any other materials or technology.
 *    If you institute patent litigation against any Licensor (including a 
 *    cross-claim or counterclaim in a lawsuit) to enforce any patents that 
 *    you allege are infringed by any Work, then your patent license from such 
 *    Licensor to the Work shall terminate as of the date such litigation is 
 *    filed.
 * 4. Redistribution
 *    You may reproduce or distribute the Work only if (a) you do so under 
 *    this License, (b) you include a complete copy of this License with your 
 *    distribution, and (c) you retain without modification any copyright, 
 *    patent, trademark, or attribution notices that are present in the Work.
 * 5. Derivative Works
 *    You may specify that additional or different terms apply to the use, 
 *    reproduction, and distribution of your derivative works of the Work 
 *    ("Your Terms") only if (a) Your Terms provide that the limitations of 
 *    Section 7 apply to your derivative works, and (b) you identify the 
 *    specific derivative works that are subject to Your Terms. 
 *    Notwithstanding Your Terms, this license (including the redistribution 
 *    requirements in Section 4) will continue to apply to the Work itself.
 * 6. Trademarks
 *    This license does not grant any rights to use any Licensor's or its 
 *    affiliates' names, logos, or trademarks, except as necessary to 
 *    reproduce the notices described in this license.
 * 7. Limitations
 *    Platform. The Work and any derivative works thereof may only be used, or 
 *    intended for use, with a Broadcom switch integrated circuit.
 *    No Reverse Engineering. You will not use the Work to disassemble, 
 *    reverse engineer, decompile, or attempt to ascertain the underlying 
 *    technology of a Broadcom switch integrated circuit.
 * 8. Termination
 *    If you violate any term of this license, then your rights under this 
 *    license (including the license grants of Sections 2 and 3) will 
 *    terminate immediately.
 * 9. Disclaimer of Warranty
 *    THE WORK IS PROVIDED "AS IS" WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 *    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OR CONDITIONS OF 
 *    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR 
 *    NON-INFRINGEMENT. YOU BEAR THE RISK OF UNDERTAKING ANY ACTIVITIES UNDER 
 *    THIS LICENSE. SOME STATES' CONSUMER LAWS DO NOT ALLOW EXCLUSION OF AN 
 *    IMPLIED WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO YOU.
 * 10. Limitation of Liability
 *    EXCEPT AS PROHIBITED BY APPLICABLE LAW, IN NO EVENT AND UNDER NO LEGAL 
 *    THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE 
 *    SHALL ANY LICENSOR BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY DIRECT, 
 *    INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF 
 *    OR RELATED TO THIS LICENSE, THE USE OR INABILITY TO USE THE WORK 
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF GOODWILL, BUSINESS INTERRUPTION, 
 *    LOST PROFITS OR DATA, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER 
 *    COMMERCIAL DAMAGES OR LOSSES), EVEN IF THE LICENSOR HAS BEEN ADVISED OF 
 *    THE POSSIBILITY OF SUCH DAMAGES.
 */

#ifndef BSL_ENUM_H
#define BSL_ENUM_H

#ifdef BSL_CONFIG_INCLUDE_CUSTOM_ENUM
#include <bsl_custom_enum.h>
#else

typedef enum bsl_severity_e {
    BSL_SEV_OFF               = 0,
    BSL_SEV_FATAL             = 1,
    BSL_SEV_ERROR             = 2,
    BSL_SEV_WARN              = 3,
    BSL_SEV_INFO              = 4,
    BSL_SEV_VERBOSE           = 5,
    BSL_SEV_DEBUG             = 6,
    BSL_SEV_COUNT             = 7
} bsl_severity_t;

#define BSL_SEVERITY_NAMES_INIT { \
    "Off", \
    "Fatal", \
    "Error", \
    "Warn", \
    "Info", \
    "Verbose", \
    "Debug" \
}

typedef enum bsl_layer_e {
    BSL_LAY_APPL              = 0,
    BSL_LAY_BCMBD             = 1,
    BSL_LAY_BCMCFG            = 2,
    BSL_LAY_BCMDRD            = 3,
    BSL_LAY_BCMECN            = 4,
    BSL_LAY_BCMEVM            = 5,
    BSL_LAY_BCMFP             = 6,
    BSL_LAY_BCMIMM            = 7,
    BSL_LAY_BCML2             = 8,
    BSL_LAY_BCMLM             = 9,
    BSL_LAY_BCMLRD            = 10,
    BSL_LAY_BCMLT             = 11,
    BSL_LAY_BCMLTM            = 12,
    BSL_LAY_BCMLTX            = 13,
    BSL_LAY_BCMMETER          = 14,
    BSL_LAY_BCMMGMT           = 15,
    BSL_LAY_BCMMIRROR         = 16,
    BSL_LAY_BCMPC             = 17,
    BSL_LAY_BCMPKT            = 18,
    BSL_LAY_BCMPORT           = 19,
    BSL_LAY_BCMPTM            = 20,
    BSL_LAY_BCMTM             = 21,
    BSL_LAY_BCMTNL            = 22,
    BSL_LAY_BCMTRM            = 23,
    BSL_LAY_BCMTRUNK          = 24,
    BSL_LAY_SHR               = 25,
    BSL_LAY_SYS               = 26,
    BSL_LAY_COUNT             = 27
} bsl_layer_t;

#define BSL_LAYER_NAMES_INIT { \
    "APPL", \
    "BCMBD", \
    "BCMCFG", \
    "BCMDRD", \
    "BCMECN", \
    "BCMEVM", \
    "BCMFP", \
    "BCMIMM", \
    "BCML2", \
    "BCMLM", \
    "BCMLRD", \
    "BCMLT", \
    "BCMLTM", \
    "BCMLTX", \
    "BCMMETER", \
    "BCMMGMT", \
    "BCMMIRROR", \
    "BCMPC", \
    "BCMPKT", \
    "BCMPORT", \
    "BCMPTM", \
    "BCMTM", \
    "BCMTNL", \
    "BCMTRM", \
    "BCMTRUNK", \
    "SHR", \
    "SYS"  \
}

typedef enum bsl_source_e {
    BSL_SRC_                  = 0,
    BSL_SRC_AVL               = 1,
    BSL_SRC_BACKEND           = 2,
    BSL_SRC_BITOP             = 3,
    BSL_SRC_BYPASS            = 4,
    BSL_SRC_CACHE             = 5,
    BSL_SRC_CCI               = 6,
    BSL_SRC_CCMDMA            = 7,
    BSL_SRC_COMMON            = 8,
    BSL_SRC_COMP              = 9,
    BSL_SRC_CTHALPM           = 10,
    BSL_SRC_CTHUFT            = 11,
    BSL_SRC_CTRL              = 12,
    BSL_SRC_DB                = 13,
    BSL_SRC_DEV               = 14,
    BSL_SRC_DMA               = 15,
    BSL_SRC_DRV               = 16,
    BSL_SRC_ECHO              = 17,
    BSL_SRC_ECMP              = 18,
    BSL_SRC_ECN_PROTOCOL      = 19,
    BSL_SRC_ENTRY             = 20,
    BSL_SRC_EP                = 21,
    BSL_SRC_EVENT             = 22,
    BSL_SRC_EXECUTIONENGINE   = 23,
    BSL_SRC_FIELDADAPTATION   = 24,
    BSL_SRC_FIFODMA           = 25,
    BSL_SRC_FP                = 26,
    BSL_SRC_FRONTEND          = 27,
    BSL_SRC_GDATA             = 28,
    BSL_SRC_GRPCREATE         = 29,
    BSL_SRC_HA                = 30,
    BSL_SRC_HAL               = 31,
    BSL_SRC_HIGHAVAILABILITY  = 32,
    BSL_SRC_HIGIG             = 33,
    BSL_SRC_IMM               = 34,
    BSL_SRC_INIT              = 35,
    BSL_SRC_INTR              = 36,
    BSL_SRC_IREQ              = 37,
    BSL_SRC_KNET              = 38,
    BSL_SRC_L2                = 39,
    BSL_SRC_L3                = 40,
    BSL_SRC_LBHDR             = 41,
    BSL_SRC_LEARN_CTRL        = 42,
    BSL_SRC_LEARN_DRV         = 43,
    BSL_SRC_LEARN_IMM         = 44,
    BSL_SRC_LOGICALRESOURCEMANAGER = 45,
    BSL_SRC_LPORT             = 46,
    BSL_SRC_LTH               = 47,
    BSL_SRC_METADATA          = 48,
    BSL_SRC_MIIM              = 49,
    BSL_SRC_MIRROR            = 50,
    BSL_SRC_MISC              = 51,
    BSL_SRC_MREQ              = 52,
    BSL_SRC_NET               = 53,
    BSL_SRC_PACKET            = 54,
    BSL_SRC_PCI               = 55,
    BSL_SRC_PHYMOD            = 56,
    BSL_SRC_PHYSICALRESOURCEMANAGER = 57,
    BSL_SRC_PKTDEV            = 58,
    BSL_SRC_PM                = 59,
    BSL_SRC_PMGR              = 60,
    BSL_SRC_PORT              = 61,
    BSL_SRC_PORT_BRIDGE       = 62,
    BSL_SRC_PORT_MEMBERSHIP_POLICY = 63,
    BSL_SRC_READ              = 64,
    BSL_SRC_RMALPM            = 65,
    BSL_SRC_RMALPMTRIE        = 66,
    BSL_SRC_RMHASH            = 67,
    BSL_SRC_RMTCAM            = 68,
    BSL_SRC_RX                = 69,
    BSL_SRC_RXPMD             = 70,
    BSL_SRC_SBUSDMA           = 71,
    BSL_SRC_SC                = 72,
    BSL_SRC_SCHAN             = 73,
    BSL_SRC_SCHANFIFO         = 74,
    BSL_SRC_SER               = 75,
    BSL_SRC_SHELL             = 76,
    BSL_SRC_SOCMEM            = 77,
    BSL_SRC_SOCREG            = 78,
    BSL_SRC_STATE             = 79,
    BSL_SRC_STG               = 80,
    BSL_SRC_SYSM              = 81,
    BSL_SRC_TABLE             = 82,
    BSL_SRC_TEST              = 83,
    BSL_SRC_TM                = 84,
    BSL_SRC_TMMGR             = 85,
    BSL_SRC_TNL               = 86,
    BSL_SRC_TOPO              = 87,
    BSL_SRC_TPACKET           = 88,
    BSL_SRC_TRANS             = 89,
    BSL_SRC_TRANSACTION       = 90,
    BSL_SRC_TRANSFORM         = 91,
    BSL_SRC_TX                = 92,
    BSL_SRC_TXPMD             = 93,
    BSL_SRC_UDF               = 94,
    BSL_SRC_UFT               = 95,
    BSL_SRC_UNET              = 96,
    BSL_SRC_VERINET           = 97,
    BSL_SRC_VLAN              = 98,
    BSL_SRC_WAL               = 99,
    BSL_SRC_WRED_UPDATE       = 100,
    BSL_SRC_COUNT             = 101
} bsl_source_t;

#define BSL_SOURCE_NAMES_INIT { \
    "", \
    "AVL", \
    "BackEnd", \
    "BitOp", \
    "ByPass", \
    "Cache", \
    "Cci", \
    "CcmDMA", \
    "Common", \
    "COMP", \
    "CthAlpm", \
    "CthUft", \
    "CTRL", \
    "DB", \
    "DEV", \
    "DMA", \
    "DRV", \
    "ECHO", \
    "ECMP", \
    "ECN_PROTOCOL", \
    "Entry", \
    "EP", \
    "Event", \
    "ExecutionEngine", \
    "FieldAdaptation", \
    "FifoDMA", \
    "FP", \
    "FrontEnd", \
    "GData", \
    "GrpCreate", \
    "HA", \
    "HAL", \
    "HighAvailability", \
    "HiGig", \
    "IMM", \
    "INIT", \
    "INTr", \
    "Ireq", \
    "KNET", \
    "L2", \
    "L3", \
    "LBHDR", \
    "LEARN_CTRL", \
    "LEARN_DRV", \
    "LEARN_IMM", \
    "LogicalResourceManager", \
    "LPORT", \
    "LTH", \
    "Metadata", \
    "MIIM", \
    "MIRROR", \
    "Misc", \
    "Mreq", \
    "NET", \
    "PacKeT", \
    "PCI", \
    "PHYMOD", \
    "PhysicalResourceManager", \
    "PKTDEV", \
    "PM", \
    "PMGR", \
    "Port", \
    "PORT_BRIDGE", \
    "PORT_MEMBERSHIP_POLICY", \
    "READ", \
    "RmAlpm", \
    "RmAlpmTrie", \
    "RmHash", \
    "RmTcam", \
    "RX", \
    "RXPMD", \
    "SbusDMA", \
    "SC", \
    "SCHAN", \
    "SchanFIFO", \
    "Ser", \
    "SHell", \
    "SocMEM", \
    "SocREG", \
    "State", \
    "STG", \
    "SYSM", \
    "TABLE", \
    "TeST", \
    "TM", \
    "TMMGR", \
    "TNL", \
    "TOPO", \
    "TPacKeT", \
    "Trans", \
    "Transaction", \
    "TRANSFORM", \
    "TX", \
    "TXPMD", \
    "UDF", \
    "Uft", \
    "UNET", \
    "VERInet", \
    "VLAN", \
    "Wal", \
    "WRED_UPDATE"  \
}

/* Short hand macros for APPL layer */
#define BSL_APPL_ECHO                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_ECHO
#define BSL_APPL_KNET                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_KNET
#define BSL_APPL_PACKET                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_PACKET
#define BSL_APPL_PKTDEV                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_PKTDEV
#define BSL_APPL_RX                     BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_RX
#define BSL_APPL_SHELL                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_SHELL
#define BSL_APPL_TEST                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_TEST
#define BSL_APPL_TX                     BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_TX
#define BSL_APPL_UNET                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_APPL, BSL_SRC_UNET

/* Sources valid for APPL layer */
#define BSL_SOURCE_APPL_VALID_INIT { \
    BSL_SRC_ECHO, \
    BSL_SRC_KNET, \
    BSL_SRC_PACKET, \
    BSL_SRC_PKTDEV, \
    BSL_SRC_RX, \
    BSL_SRC_SHELL, \
    BSL_SRC_TEST, \
    BSL_SRC_TX, \
    BSL_SRC_UNET, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMBD layer */
#define BSL_BCMBD_BYPASS                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_BYPASS
#define BSL_BCMBD_CCMDMA                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_CCMDMA
#define BSL_BCMBD_DEV                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_DEV
#define BSL_BCMBD_DMA                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_DMA
#define BSL_BCMBD_FIFODMA               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_FIFODMA
#define BSL_BCMBD_INIT                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_INIT
#define BSL_BCMBD_INTR                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_INTR
#define BSL_BCMBD_MIIM                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_MIIM
#define BSL_BCMBD_SBUSDMA               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_SBUSDMA
#define BSL_BCMBD_SCHAN                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_SCHAN
#define BSL_BCMBD_SCHANFIFO             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_SCHANFIFO
#define BSL_BCMBD_SOCMEM                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_SOCMEM
#define BSL_BCMBD_SOCREG                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMBD, BSL_SRC_SOCREG

/* Sources valid for BCMBD layer */
#define BSL_SOURCE_BCMBD_VALID_INIT { \
    BSL_SRC_BYPASS, \
    BSL_SRC_CCMDMA, \
    BSL_SRC_DEV, \
    BSL_SRC_DMA, \
    BSL_SRC_FIFODMA, \
    BSL_SRC_INIT, \
    BSL_SRC_INTR, \
    BSL_SRC_MIIM, \
    BSL_SRC_SBUSDMA, \
    BSL_SRC_SCHAN, \
    BSL_SRC_SCHANFIFO, \
    BSL_SRC_SOCMEM, \
    BSL_SRC_SOCREG, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMCFG layer */
#define BSL_BCMCFG_COMP                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMCFG, BSL_SRC_COMP
#define BSL_BCMCFG_DEV                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMCFG, BSL_SRC_DEV
#define BSL_BCMCFG_INIT                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMCFG, BSL_SRC_INIT
#define BSL_BCMCFG_READ                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMCFG, BSL_SRC_READ
#define BSL_BCMCFG_TABLE                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMCFG, BSL_SRC_TABLE

/* Sources valid for BCMCFG layer */
#define BSL_SOURCE_BCMCFG_VALID_INIT { \
    BSL_SRC_COMP, \
    BSL_SRC_DEV, \
    BSL_SRC_INIT, \
    BSL_SRC_READ, \
    BSL_SRC_TABLE, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMDRD layer */
#define BSL_BCMDRD_BYPASS               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMDRD, BSL_SRC_BYPASS
#define BSL_BCMDRD_DEV                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMDRD, BSL_SRC_DEV
#define BSL_BCMDRD_HAL                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMDRD, BSL_SRC_HAL

/* Sources valid for BCMDRD layer */
#define BSL_SOURCE_BCMDRD_VALID_INIT { \
    BSL_SRC_BYPASS, \
    BSL_SRC_DEV, \
    BSL_SRC_HAL, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMECN layer */
#define BSL_BCMECN_ECN_PROTOCOL         BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMECN, BSL_SRC_ECN_PROTOCOL
#define BSL_BCMECN_WRED_UPDATE          BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMECN, BSL_SRC_WRED_UPDATE

/* Sources valid for BCMECN layer */
#define BSL_SOURCE_BCMECN_VALID_INIT { \
    BSL_SRC_ECN_PROTOCOL, \
    BSL_SRC_WRED_UPDATE, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMEVM layer */
#define BSL_BCMEVM_EVENT                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMEVM, BSL_SRC_EVENT

/* Sources valid for BCMEVM layer */
#define BSL_SOURCE_BCMEVM_VALID_INIT { \
    BSL_SRC_EVENT, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMFP layer */
#define BSL_BCMFP_COMMON                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMFP, BSL_SRC_COMMON
#define BSL_BCMFP_GRPCREATE             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMFP, BSL_SRC_GRPCREATE
#define BSL_BCMFP_HA                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMFP, BSL_SRC_HA
#define BSL_BCMFP_INIT                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMFP, BSL_SRC_INIT
#define BSL_BCMFP_TRANS                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMFP, BSL_SRC_TRANS

/* Sources valid for BCMFP layer */
#define BSL_SOURCE_BCMFP_VALID_INIT { \
    BSL_SRC_COMMON, \
    BSL_SRC_GRPCREATE, \
    BSL_SRC_HA, \
    BSL_SRC_INIT, \
    BSL_SRC_TRANS, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMIMM layer */
#define BSL_BCMIMM_BACKEND              BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMIMM, BSL_SRC_BACKEND
#define BSL_BCMIMM_FRONTEND             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMIMM, BSL_SRC_FRONTEND

/* Sources valid for BCMIMM layer */
#define BSL_SOURCE_BCMIMM_VALID_INIT { \
    BSL_SRC_BACKEND, \
    BSL_SRC_FRONTEND, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCML2 layer */
#define BSL_BCML2_LEARN_CTRL            BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCML2, BSL_SRC_LEARN_CTRL
#define BSL_BCML2_LEARN_DRV             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCML2, BSL_SRC_LEARN_DRV
#define BSL_BCML2_LEARN_IMM             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCML2, BSL_SRC_LEARN_IMM
#define BSL_BCML2_SYSM                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCML2, BSL_SRC_SYSM
#define BSL_BCML2_TABLE                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCML2, BSL_SRC_TABLE
#define BSL_BCML2_TRANSFORM             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCML2, BSL_SRC_TRANSFORM

/* Sources valid for BCML2 layer */
#define BSL_SOURCE_BCML2_VALID_INIT { \
    BSL_SRC_LEARN_CTRL, \
    BSL_SRC_LEARN_DRV, \
    BSL_SRC_LEARN_IMM, \
    BSL_SRC_SYSM, \
    BSL_SRC_TABLE, \
    BSL_SRC_TRANSFORM, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMLM layer */
#define BSL_BCMLM_CTRL                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLM, BSL_SRC_CTRL
#define BSL_BCMLM_DRV                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLM, BSL_SRC_DRV
#define BSL_BCMLM_IMM                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLM, BSL_SRC_IMM
#define BSL_BCMLM_INIT                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLM, BSL_SRC_INIT
#define BSL_BCMLM_SYSM                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLM, BSL_SRC_SYSM

/* Sources valid for BCMLM layer */
#define BSL_SOURCE_BCMLM_VALID_INIT { \
    BSL_SRC_CTRL, \
    BSL_SRC_DRV, \
    BSL_SRC_IMM, \
    BSL_SRC_INIT, \
    BSL_SRC_SYSM, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMLRD layer */
#define BSL_BCMLRD_SYSM                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLRD, BSL_SRC_SYSM

/* Sources valid for BCMLRD layer */
#define BSL_SOURCE_BCMLRD_VALID_INIT { \
    BSL_SRC_SYSM, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMLT layer */
#define BSL_BCMLT_ENTRY                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLT, BSL_SRC_ENTRY
#define BSL_BCMLT_TABLE                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLT, BSL_SRC_TABLE
#define BSL_BCMLT_TRANSACTION           BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLT, BSL_SRC_TRANSACTION

/* Sources valid for BCMLT layer */
#define BSL_SOURCE_BCMLT_VALID_INIT { \
    BSL_SRC_ENTRY, \
    BSL_SRC_TABLE, \
    BSL_SRC_TRANSACTION, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMLTM layer */
#define BSL_BCMLTM_ENTRY                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_ENTRY
#define BSL_BCMLTM_EXECUTIONENGINE      BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_EXECUTIONENGINE
#define BSL_BCMLTM_FIELDADAPTATION      BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_FIELDADAPTATION
#define BSL_BCMLTM_HIGHAVAILABILITY     BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_HIGHAVAILABILITY
#define BSL_BCMLTM_INIT                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_INIT
#define BSL_BCMLTM_LOGICALRESOURCEMANAGER BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_LOGICALRESOURCEMANAGER
#define BSL_BCMLTM_METADATA             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_METADATA
#define BSL_BCMLTM_STATE                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_STATE
#define BSL_BCMLTM_TRANSACTION          BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTM, BSL_SRC_TRANSACTION

/* Sources valid for BCMLTM layer */
#define BSL_SOURCE_BCMLTM_VALID_INIT { \
    BSL_SRC_ENTRY, \
    BSL_SRC_EXECUTIONENGINE, \
    BSL_SRC_FIELDADAPTATION, \
    BSL_SRC_HIGHAVAILABILITY, \
    BSL_SRC_INIT, \
    BSL_SRC_LOGICALRESOURCEMANAGER, \
    BSL_SRC_METADATA, \
    BSL_SRC_STATE, \
    BSL_SRC_TRANSACTION, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMLTX layer */
#define BSL_BCMLTX_COMMON               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_COMMON
#define BSL_BCMLTX_ECMP                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_ECMP
#define BSL_BCMLTX_EP                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_EP
#define BSL_BCMLTX_L2                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_L2
#define BSL_BCMLTX_L3                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_L3
#define BSL_BCMLTX_PORT                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_PORT
#define BSL_BCMLTX_STG                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_STG
#define BSL_BCMLTX_TM                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_TM
#define BSL_BCMLTX_TNL                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_TNL
#define BSL_BCMLTX_UDF                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_UDF
#define BSL_BCMLTX_VLAN                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMLTX, BSL_SRC_VLAN

/* Sources valid for BCMLTX layer */
#define BSL_SOURCE_BCMLTX_VALID_INIT { \
    BSL_SRC_COMMON, \
    BSL_SRC_ECMP, \
    BSL_SRC_EP, \
    BSL_SRC_L2, \
    BSL_SRC_L3, \
    BSL_SRC_PORT, \
    BSL_SRC_STG, \
    BSL_SRC_TM, \
    BSL_SRC_TNL, \
    BSL_SRC_UDF, \
    BSL_SRC_VLAN, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMMETER layer */
#define BSL_BCMMETER_COMMON             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMETER, BSL_SRC_COMMON
#define BSL_BCMMETER_FP                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMETER, BSL_SRC_FP
#define BSL_BCMMETER_INIT               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMETER, BSL_SRC_INIT
#define BSL_BCMMETER_SC                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMETER, BSL_SRC_SC

/* Sources valid for BCMMETER layer */
#define BSL_SOURCE_BCMMETER_VALID_INIT { \
    BSL_SRC_COMMON, \
    BSL_SRC_FP, \
    BSL_SRC_INIT, \
    BSL_SRC_SC, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMMGMT layer */
#define BSL_BCMMGMT_DEV                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMGMT, BSL_SRC_DEV
#define BSL_BCMMGMT_INIT                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMGMT, BSL_SRC_INIT
#define BSL_BCMMGMT_SYSM                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMGMT, BSL_SRC_SYSM

/* Sources valid for BCMMGMT layer */
#define BSL_SOURCE_BCMMGMT_VALID_INIT { \
    BSL_SRC_DEV, \
    BSL_SRC_INIT, \
    BSL_SRC_SYSM, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMMIRROR layer */
#define BSL_BCMMIRROR_COMMON            BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMIRROR, BSL_SRC_COMMON
#define BSL_BCMMIRROR_DEV               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMIRROR, BSL_SRC_DEV
#define BSL_BCMMIRROR_INIT              BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMMIRROR, BSL_SRC_INIT

/* Sources valid for BCMMIRROR layer */
#define BSL_SOURCE_BCMMIRROR_VALID_INIT { \
    BSL_SRC_COMMON, \
    BSL_SRC_DEV, \
    BSL_SRC_INIT, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMPC layer */
#define BSL_BCMPC_DB                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_DB
#define BSL_BCMPC_DEV                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_DEV
#define BSL_BCMPC_IMM                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_IMM
#define BSL_BCMPC_INIT                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_INIT
#define BSL_BCMPC_LPORT                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_LPORT
#define BSL_BCMPC_LTH                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_LTH
#define BSL_BCMPC_PHYMOD                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_PHYMOD
#define BSL_BCMPC_PM                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_PM
#define BSL_BCMPC_PMGR                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_PMGR
#define BSL_BCMPC_TOPO                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPC, BSL_SRC_TOPO

/* Sources valid for BCMPC layer */
#define BSL_SOURCE_BCMPC_VALID_INIT { \
    BSL_SRC_DB, \
    BSL_SRC_DEV, \
    BSL_SRC_IMM, \
    BSL_SRC_INIT, \
    BSL_SRC_LPORT, \
    BSL_SRC_LTH, \
    BSL_SRC_PHYMOD, \
    BSL_SRC_PM, \
    BSL_SRC_PMGR, \
    BSL_SRC_TOPO, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMPKT layer */
#define BSL_BCMPKT_DEV                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_DEV
#define BSL_BCMPKT_DMA                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_DMA
#define BSL_BCMPKT_HIGIG                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_HIGIG
#define BSL_BCMPKT_KNET                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_KNET
#define BSL_BCMPKT_LBHDR                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_LBHDR
#define BSL_BCMPKT_NET                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_NET
#define BSL_BCMPKT_PACKET               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_PACKET
#define BSL_BCMPKT_RX                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_RX
#define BSL_BCMPKT_RXPMD                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_RXPMD
#define BSL_BCMPKT_TX                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_TX
#define BSL_BCMPKT_TXPMD                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_TXPMD
#define BSL_BCMPKT_UNET                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPKT, BSL_SRC_UNET

/* Sources valid for BCMPKT layer */
#define BSL_SOURCE_BCMPKT_VALID_INIT { \
    BSL_SRC_DEV, \
    BSL_SRC_DMA, \
    BSL_SRC_HIGIG, \
    BSL_SRC_KNET, \
    BSL_SRC_LBHDR, \
    BSL_SRC_NET, \
    BSL_SRC_PACKET, \
    BSL_SRC_RX, \
    BSL_SRC_RXPMD, \
    BSL_SRC_TX, \
    BSL_SRC_TXPMD, \
    BSL_SRC_UNET, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMPORT layer */
#define BSL_BCMPORT_IMM                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPORT, BSL_SRC_IMM
#define BSL_BCMPORT_MIRROR              BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPORT, BSL_SRC_MIRROR
#define BSL_BCMPORT_PORT_BRIDGE         BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPORT, BSL_SRC_PORT_BRIDGE
#define BSL_BCMPORT_PORT_MEMBERSHIP_POLICY BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPORT, BSL_SRC_PORT_MEMBERSHIP_POLICY
#define BSL_BCMPORT_SYSM                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPORT, BSL_SRC_SYSM
#define BSL_BCMPORT_TABLE               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPORT, BSL_SRC_TABLE

/* Sources valid for BCMPORT layer */
#define BSL_SOURCE_BCMPORT_VALID_INIT { \
    BSL_SRC_IMM, \
    BSL_SRC_MIRROR, \
    BSL_SRC_PORT_BRIDGE, \
    BSL_SRC_PORT_MEMBERSHIP_POLICY, \
    BSL_SRC_SYSM, \
    BSL_SRC_TABLE, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMPTM layer */
#define BSL_BCMPTM_CACHE                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_CACHE
#define BSL_BCMPTM_CCI                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_CCI
#define BSL_BCMPTM_CTHALPM              BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_CTHALPM
#define BSL_BCMPTM_CTHUFT               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_CTHUFT
#define BSL_BCMPTM_ENTRY                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_ENTRY
#define BSL_BCMPTM_IREQ                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_IREQ
#define BSL_BCMPTM_METADATA             BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_METADATA
#define BSL_BCMPTM_MISC                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_MISC
#define BSL_BCMPTM_MREQ                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_MREQ
#define BSL_BCMPTM_PHYSICALRESOURCEMANAGER BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_PHYSICALRESOURCEMANAGER
#define BSL_BCMPTM_RMALPM               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_RMALPM
#define BSL_BCMPTM_RMALPMTRIE           BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_RMALPMTRIE
#define BSL_BCMPTM_RMHASH               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_RMHASH
#define BSL_BCMPTM_RMTCAM               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_RMTCAM
#define BSL_BCMPTM_SER                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_SER
#define BSL_BCMPTM_TRANSACTION          BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_TRANSACTION
#define BSL_BCMPTM_UFT                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_UFT
#define BSL_BCMPTM_WAL                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMPTM, BSL_SRC_WAL

/* Sources valid for BCMPTM layer */
#define BSL_SOURCE_BCMPTM_VALID_INIT { \
    BSL_SRC_CACHE, \
    BSL_SRC_CCI, \
    BSL_SRC_CTHALPM, \
    BSL_SRC_CTHUFT, \
    BSL_SRC_ENTRY, \
    BSL_SRC_IREQ, \
    BSL_SRC_METADATA, \
    BSL_SRC_MISC, \
    BSL_SRC_MREQ, \
    BSL_SRC_PHYSICALRESOURCEMANAGER, \
    BSL_SRC_RMALPM, \
    BSL_SRC_RMALPMTRIE, \
    BSL_SRC_RMHASH, \
    BSL_SRC_RMTCAM, \
    BSL_SRC_SER, \
    BSL_SRC_TRANSACTION, \
    BSL_SRC_UFT, \
    BSL_SRC_WAL, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMTM layer */
#define BSL_BCMTM_                      BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTM, BSL_SRC_
#define BSL_BCMTM_INIT                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTM, BSL_SRC_INIT
#define BSL_BCMTM_LTH                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTM, BSL_SRC_LTH
#define BSL_BCMTM_TMMGR                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTM, BSL_SRC_TMMGR

/* Sources valid for BCMTM layer */
#define BSL_SOURCE_BCMTM_VALID_INIT { \
    BSL_SRC_, \
    BSL_SRC_INIT, \
    BSL_SRC_LTH, \
    BSL_SRC_TMMGR, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMTNL layer */
#define BSL_BCMTNL_COMMON               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTNL, BSL_SRC_COMMON

/* Sources valid for BCMTNL layer */
#define BSL_SOURCE_BCMTNL_VALID_INIT { \
    BSL_SRC_COMMON, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMTRM layer */
#define BSL_BCMTRM_ENTRY                BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTRM, BSL_SRC_ENTRY
#define BSL_BCMTRM_TRANSACTION          BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTRM, BSL_SRC_TRANSACTION

/* Sources valid for BCMTRM layer */
#define BSL_SOURCE_BCMTRM_VALID_INIT { \
    BSL_SRC_ENTRY, \
    BSL_SRC_TRANSACTION, \
    BSL_SRC_COUNT \
}

/* Short hand macros for BCMTRUNK layer */
#define BSL_BCMTRUNK_SYSM               BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTRUNK, BSL_SRC_SYSM
#define BSL_BCMTRUNK_TABLE              BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_BCMTRUNK, BSL_SRC_TABLE

/* Sources valid for BCMTRUNK layer */
#define BSL_SOURCE_BCMTRUNK_VALID_INIT { \
    BSL_SRC_SYSM, \
    BSL_SRC_TABLE, \
    BSL_SRC_COUNT \
}

/* Short hand macros for SHR layer */
#define BSL_SHR_AVL                     BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SHR, BSL_SRC_AVL
#define BSL_SHR_BITOP                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SHR, BSL_SRC_BITOP
#define BSL_SHR_GDATA                   BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SHR, BSL_SRC_GDATA
#define BSL_SHR_HA                      BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SHR, BSL_SRC_HA
#define BSL_SHR_SYSM                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SHR, BSL_SRC_SYSM

/* Sources valid for SHR layer */
#define BSL_SOURCE_SHR_VALID_INIT { \
    BSL_SRC_AVL, \
    BSL_SRC_BITOP, \
    BSL_SRC_GDATA, \
    BSL_SRC_HA, \
    BSL_SRC_SYSM, \
    BSL_SRC_COUNT \
}

/* Short hand macros for SYS layer */
#define BSL_SYS_DMA                     BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_DMA
#define BSL_SYS_INTR                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_INTR
#define BSL_SYS_KNET                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_KNET
#define BSL_SYS_PACKET                  BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_PACKET
#define BSL_SYS_PCI                     BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_PCI
#define BSL_SYS_RX                      BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_RX
#define BSL_SYS_TPACKET                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_TPACKET
#define BSL_SYS_TX                      BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_TX
#define BSL_SYS_UNET                    BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_UNET
#define BSL_SYS_VERINET                 BSL_FILE, BSL_LINE, BSL_FUNC, BSL_LAY_SYS, BSL_SRC_VERINET

/* Sources valid for SYS layer */
#define BSL_SOURCE_SYS_VALID_INIT { \
    BSL_SRC_DMA, \
    BSL_SRC_INTR, \
    BSL_SRC_KNET, \
    BSL_SRC_PACKET, \
    BSL_SRC_PCI, \
    BSL_SRC_RX, \
    BSL_SRC_TPACKET, \
    BSL_SRC_TX, \
    BSL_SRC_UNET, \
    BSL_SRC_VERINET, \
    BSL_SRC_COUNT \
}

/* Organize layer/source/severity in a single 32-bit word */
#define BSL_LAYER_SHFT          24
#define BSL_LAYER_MASK          0xff
#define BSL_SOURCE_SHFT         8
#define BSL_SOURCE_MASK         0xffff
#define BSL_SEVERITY_SHFT       0
#define BSL_SEVERITY_MASK       0xff

/* Get elements of packed meta data */
#define BSL_LAYER_GET(chk_) \
    (((chk_) >> BSL_LAYER_SHFT) & BSL_LAYER_MASK)
#define BSL_SOURCE_GET(chk_) \
    (((chk_) >> BSL_SOURCE_SHFT) & BSL_SOURCE_MASK)
#define BSL_SEVERITY_GET(chk_) \
    (((chk_) >> BSL_SEVERITY_SHFT) & BSL_SEVERITY_MASK)

/* Encode elements for packed meta data */
#define BSL_LAYER_ENC(layer_) \
    ((layer_) << BSL_LAYER_SHFT)
#define BSL_SOURCE_ENC(source_) \
    ((source_) << BSL_SOURCE_SHFT)
#define BSL_SEVERITY_ENC(severity_) \
    ((severity_) << BSL_SEVERITY_SHFT)

/* Severity defines for LOG_* macros */
#define BSL_FATAL               BSL_SEVERITY_ENC(BSL_SEV_FATAL)
#define BSL_ERROR               BSL_SEVERITY_ENC(BSL_SEV_ERROR)
#define BSL_WARN                BSL_SEVERITY_ENC(BSL_SEV_WARN)
#define BSL_INFO                BSL_SEVERITY_ENC(BSL_SEV_INFO)
#define BSL_VERBOSE             BSL_SEVERITY_ENC(BSL_SEV_VERBOSE)
#define BSL_DEBUG               BSL_SEVERITY_ENC(BSL_SEV_DEBUG)

/* Layer defines for LOG_* macros */
#define BSL_L_APPL              BSL_LAYER_ENC(BSL_LAY_APPL)
#define BSL_L_BCMBD             BSL_LAYER_ENC(BSL_LAY_BCMBD)
#define BSL_L_BCMCFG            BSL_LAYER_ENC(BSL_LAY_BCMCFG)
#define BSL_L_BCMDRD            BSL_LAYER_ENC(BSL_LAY_BCMDRD)
#define BSL_L_BCMECN            BSL_LAYER_ENC(BSL_LAY_BCMECN)
#define BSL_L_BCMEVM            BSL_LAYER_ENC(BSL_LAY_BCMEVM)
#define BSL_L_BCMFP             BSL_LAYER_ENC(BSL_LAY_BCMFP)
#define BSL_L_BCMIMM            BSL_LAYER_ENC(BSL_LAY_BCMIMM)
#define BSL_L_BCML2             BSL_LAYER_ENC(BSL_LAY_BCML2)
#define BSL_L_BCMLM             BSL_LAYER_ENC(BSL_LAY_BCMLM)
#define BSL_L_BCMLRD            BSL_LAYER_ENC(BSL_LAY_BCMLRD)
#define BSL_L_BCMLT             BSL_LAYER_ENC(BSL_LAY_BCMLT)
#define BSL_L_BCMLTM            BSL_LAYER_ENC(BSL_LAY_BCMLTM)
#define BSL_L_BCMLTX            BSL_LAYER_ENC(BSL_LAY_BCMLTX)
#define BSL_L_BCMMETER          BSL_LAYER_ENC(BSL_LAY_BCMMETER)
#define BSL_L_BCMMGMT           BSL_LAYER_ENC(BSL_LAY_BCMMGMT)
#define BSL_L_BCMMIRROR         BSL_LAYER_ENC(BSL_LAY_BCMMIRROR)
#define BSL_L_BCMPC             BSL_LAYER_ENC(BSL_LAY_BCMPC)
#define BSL_L_BCMPKT            BSL_LAYER_ENC(BSL_LAY_BCMPKT)
#define BSL_L_BCMPORT           BSL_LAYER_ENC(BSL_LAY_BCMPORT)
#define BSL_L_BCMPTM            BSL_LAYER_ENC(BSL_LAY_BCMPTM)
#define BSL_L_BCMTM             BSL_LAYER_ENC(BSL_LAY_BCMTM)
#define BSL_L_BCMTNL            BSL_LAYER_ENC(BSL_LAY_BCMTNL)
#define BSL_L_BCMTRM            BSL_LAYER_ENC(BSL_LAY_BCMTRM)
#define BSL_L_BCMTRUNK          BSL_LAYER_ENC(BSL_LAY_BCMTRUNK)
#define BSL_L_SHR               BSL_LAYER_ENC(BSL_LAY_SHR)
#define BSL_L_SYS               BSL_LAYER_ENC(BSL_LAY_SYS)

/* Source defines for LOG_* macros */
#define BSL_S_                  BSL_SOURCE_ENC(BSL_SRC_)
#define BSL_S_AVL               BSL_SOURCE_ENC(BSL_SRC_AVL)
#define BSL_S_BACKEND           BSL_SOURCE_ENC(BSL_SRC_BACKEND)
#define BSL_S_BITOP             BSL_SOURCE_ENC(BSL_SRC_BITOP)
#define BSL_S_BYPASS            BSL_SOURCE_ENC(BSL_SRC_BYPASS)
#define BSL_S_CACHE             BSL_SOURCE_ENC(BSL_SRC_CACHE)
#define BSL_S_CCI               BSL_SOURCE_ENC(BSL_SRC_CCI)
#define BSL_S_CCMDMA            BSL_SOURCE_ENC(BSL_SRC_CCMDMA)
#define BSL_S_COMMON            BSL_SOURCE_ENC(BSL_SRC_COMMON)
#define BSL_S_COMP              BSL_SOURCE_ENC(BSL_SRC_COMP)
#define BSL_S_CTHALPM           BSL_SOURCE_ENC(BSL_SRC_CTHALPM)
#define BSL_S_CTHUFT            BSL_SOURCE_ENC(BSL_SRC_CTHUFT)
#define BSL_S_CTRL              BSL_SOURCE_ENC(BSL_SRC_CTRL)
#define BSL_S_DB                BSL_SOURCE_ENC(BSL_SRC_DB)
#define BSL_S_DEV               BSL_SOURCE_ENC(BSL_SRC_DEV)
#define BSL_S_DMA               BSL_SOURCE_ENC(BSL_SRC_DMA)
#define BSL_S_DRV               BSL_SOURCE_ENC(BSL_SRC_DRV)
#define BSL_S_ECHO              BSL_SOURCE_ENC(BSL_SRC_ECHO)
#define BSL_S_ECMP              BSL_SOURCE_ENC(BSL_SRC_ECMP)
#define BSL_S_ECN_PROTOCOL      BSL_SOURCE_ENC(BSL_SRC_ECN_PROTOCOL)
#define BSL_S_ENTRY             BSL_SOURCE_ENC(BSL_SRC_ENTRY)
#define BSL_S_EP                BSL_SOURCE_ENC(BSL_SRC_EP)
#define BSL_S_EVENT             BSL_SOURCE_ENC(BSL_SRC_EVENT)
#define BSL_S_EXECUTIONENGINE   BSL_SOURCE_ENC(BSL_SRC_EXECUTIONENGINE)
#define BSL_S_FIELDADAPTATION   BSL_SOURCE_ENC(BSL_SRC_FIELDADAPTATION)
#define BSL_S_FIFODMA           BSL_SOURCE_ENC(BSL_SRC_FIFODMA)
#define BSL_S_FP                BSL_SOURCE_ENC(BSL_SRC_FP)
#define BSL_S_FRONTEND          BSL_SOURCE_ENC(BSL_SRC_FRONTEND)
#define BSL_S_GDATA             BSL_SOURCE_ENC(BSL_SRC_GDATA)
#define BSL_S_GRPCREATE         BSL_SOURCE_ENC(BSL_SRC_GRPCREATE)
#define BSL_S_HA                BSL_SOURCE_ENC(BSL_SRC_HA)
#define BSL_S_HAL               BSL_SOURCE_ENC(BSL_SRC_HAL)
#define BSL_S_HIGHAVAILABILITY  BSL_SOURCE_ENC(BSL_SRC_HIGHAVAILABILITY)
#define BSL_S_HIGIG             BSL_SOURCE_ENC(BSL_SRC_HIGIG)
#define BSL_S_IMM               BSL_SOURCE_ENC(BSL_SRC_IMM)
#define BSL_S_INIT              BSL_SOURCE_ENC(BSL_SRC_INIT)
#define BSL_S_INTR              BSL_SOURCE_ENC(BSL_SRC_INTR)
#define BSL_S_IREQ              BSL_SOURCE_ENC(BSL_SRC_IREQ)
#define BSL_S_KNET              BSL_SOURCE_ENC(BSL_SRC_KNET)
#define BSL_S_L2                BSL_SOURCE_ENC(BSL_SRC_L2)
#define BSL_S_L3                BSL_SOURCE_ENC(BSL_SRC_L3)
#define BSL_S_LBHDR             BSL_SOURCE_ENC(BSL_SRC_LBHDR)
#define BSL_S_LEARN_CTRL        BSL_SOURCE_ENC(BSL_SRC_LEARN_CTRL)
#define BSL_S_LEARN_DRV         BSL_SOURCE_ENC(BSL_SRC_LEARN_DRV)
#define BSL_S_LEARN_IMM         BSL_SOURCE_ENC(BSL_SRC_LEARN_IMM)
#define BSL_S_LOGICALRESOURCEMANAGER BSL_SOURCE_ENC(BSL_SRC_LOGICALRESOURCEMANAGER)
#define BSL_S_LPORT             BSL_SOURCE_ENC(BSL_SRC_LPORT)
#define BSL_S_LTH               BSL_SOURCE_ENC(BSL_SRC_LTH)
#define BSL_S_METADATA          BSL_SOURCE_ENC(BSL_SRC_METADATA)
#define BSL_S_MIIM              BSL_SOURCE_ENC(BSL_SRC_MIIM)
#define BSL_S_MIRROR            BSL_SOURCE_ENC(BSL_SRC_MIRROR)
#define BSL_S_MISC              BSL_SOURCE_ENC(BSL_SRC_MISC)
#define BSL_S_MREQ              BSL_SOURCE_ENC(BSL_SRC_MREQ)
#define BSL_S_NET               BSL_SOURCE_ENC(BSL_SRC_NET)
#define BSL_S_PACKET            BSL_SOURCE_ENC(BSL_SRC_PACKET)
#define BSL_S_PCI               BSL_SOURCE_ENC(BSL_SRC_PCI)
#define BSL_S_PHYMOD            BSL_SOURCE_ENC(BSL_SRC_PHYMOD)
#define BSL_S_PHYSICALRESOURCEMANAGER BSL_SOURCE_ENC(BSL_SRC_PHYSICALRESOURCEMANAGER)
#define BSL_S_PKTDEV            BSL_SOURCE_ENC(BSL_SRC_PKTDEV)
#define BSL_S_PM                BSL_SOURCE_ENC(BSL_SRC_PM)
#define BSL_S_PMGR              BSL_SOURCE_ENC(BSL_SRC_PMGR)
#define BSL_S_PORT              BSL_SOURCE_ENC(BSL_SRC_PORT)
#define BSL_S_PORT_BRIDGE       BSL_SOURCE_ENC(BSL_SRC_PORT_BRIDGE)
#define BSL_S_PORT_MEMBERSHIP_POLICY BSL_SOURCE_ENC(BSL_SRC_PORT_MEMBERSHIP_POLICY)
#define BSL_S_READ              BSL_SOURCE_ENC(BSL_SRC_READ)
#define BSL_S_RMALPM            BSL_SOURCE_ENC(BSL_SRC_RMALPM)
#define BSL_S_RMALPMTRIE        BSL_SOURCE_ENC(BSL_SRC_RMALPMTRIE)
#define BSL_S_RMHASH            BSL_SOURCE_ENC(BSL_SRC_RMHASH)
#define BSL_S_RMTCAM            BSL_SOURCE_ENC(BSL_SRC_RMTCAM)
#define BSL_S_RX                BSL_SOURCE_ENC(BSL_SRC_RX)
#define BSL_S_RXPMD             BSL_SOURCE_ENC(BSL_SRC_RXPMD)
#define BSL_S_SBUSDMA           BSL_SOURCE_ENC(BSL_SRC_SBUSDMA)
#define BSL_S_SC                BSL_SOURCE_ENC(BSL_SRC_SC)
#define BSL_S_SCHAN             BSL_SOURCE_ENC(BSL_SRC_SCHAN)
#define BSL_S_SCHANFIFO         BSL_SOURCE_ENC(BSL_SRC_SCHANFIFO)
#define BSL_S_SER               BSL_SOURCE_ENC(BSL_SRC_SER)
#define BSL_S_SHELL             BSL_SOURCE_ENC(BSL_SRC_SHELL)
#define BSL_S_SOCMEM            BSL_SOURCE_ENC(BSL_SRC_SOCMEM)
#define BSL_S_SOCREG            BSL_SOURCE_ENC(BSL_SRC_SOCREG)
#define BSL_S_STATE             BSL_SOURCE_ENC(BSL_SRC_STATE)
#define BSL_S_STG               BSL_SOURCE_ENC(BSL_SRC_STG)
#define BSL_S_SYSM              BSL_SOURCE_ENC(BSL_SRC_SYSM)
#define BSL_S_TABLE             BSL_SOURCE_ENC(BSL_SRC_TABLE)
#define BSL_S_TEST              BSL_SOURCE_ENC(BSL_SRC_TEST)
#define BSL_S_TM                BSL_SOURCE_ENC(BSL_SRC_TM)
#define BSL_S_TMMGR             BSL_SOURCE_ENC(BSL_SRC_TMMGR)
#define BSL_S_TNL               BSL_SOURCE_ENC(BSL_SRC_TNL)
#define BSL_S_TOPO              BSL_SOURCE_ENC(BSL_SRC_TOPO)
#define BSL_S_TPACKET           BSL_SOURCE_ENC(BSL_SRC_TPACKET)
#define BSL_S_TRANS             BSL_SOURCE_ENC(BSL_SRC_TRANS)
#define BSL_S_TRANSACTION       BSL_SOURCE_ENC(BSL_SRC_TRANSACTION)
#define BSL_S_TRANSFORM         BSL_SOURCE_ENC(BSL_SRC_TRANSFORM)
#define BSL_S_TX                BSL_SOURCE_ENC(BSL_SRC_TX)
#define BSL_S_TXPMD             BSL_SOURCE_ENC(BSL_SRC_TXPMD)
#define BSL_S_UDF               BSL_SOURCE_ENC(BSL_SRC_UDF)
#define BSL_S_UFT               BSL_SOURCE_ENC(BSL_SRC_UFT)
#define BSL_S_UNET              BSL_SOURCE_ENC(BSL_SRC_UNET)
#define BSL_S_VERINET           BSL_SOURCE_ENC(BSL_SRC_VERINET)
#define BSL_S_VLAN              BSL_SOURCE_ENC(BSL_SRC_VLAN)
#define BSL_S_WAL               BSL_SOURCE_ENC(BSL_SRC_WAL)
#define BSL_S_WRED_UPDATE       BSL_SOURCE_ENC(BSL_SRC_WRED_UPDATE)

/* Combined layer/sources for APPL layer */
#define BSL_LS_APPL_ECHO                (BSL_L_APPL | BSL_S_ECHO)
#define BSL_LS_APPL_KNET                (BSL_L_APPL | BSL_S_KNET)
#define BSL_LS_APPL_PACKET              (BSL_L_APPL | BSL_S_PACKET)
#define BSL_LS_APPL_PKTDEV              (BSL_L_APPL | BSL_S_PKTDEV)
#define BSL_LS_APPL_RX                  (BSL_L_APPL | BSL_S_RX)
#define BSL_LS_APPL_SHELL               (BSL_L_APPL | BSL_S_SHELL)
#define BSL_LS_APPL_TEST                (BSL_L_APPL | BSL_S_TEST)
#define BSL_LS_APPL_TX                  (BSL_L_APPL | BSL_S_TX)
#define BSL_LS_APPL_UNET                (BSL_L_APPL | BSL_S_UNET)

/* Combined layer/sources for BCMBD layer */
#define BSL_LS_BCMBD_BYPASS             (BSL_L_BCMBD | BSL_S_BYPASS)
#define BSL_LS_BCMBD_CCMDMA             (BSL_L_BCMBD | BSL_S_CCMDMA)
#define BSL_LS_BCMBD_DEV                (BSL_L_BCMBD | BSL_S_DEV)
#define BSL_LS_BCMBD_DMA                (BSL_L_BCMBD | BSL_S_DMA)
#define BSL_LS_BCMBD_FIFODMA            (BSL_L_BCMBD | BSL_S_FIFODMA)
#define BSL_LS_BCMBD_INIT               (BSL_L_BCMBD | BSL_S_INIT)
#define BSL_LS_BCMBD_INTR               (BSL_L_BCMBD | BSL_S_INTR)
#define BSL_LS_BCMBD_MIIM               (BSL_L_BCMBD | BSL_S_MIIM)
#define BSL_LS_BCMBD_SBUSDMA            (BSL_L_BCMBD | BSL_S_SBUSDMA)
#define BSL_LS_BCMBD_SCHAN              (BSL_L_BCMBD | BSL_S_SCHAN)
#define BSL_LS_BCMBD_SCHANFIFO          (BSL_L_BCMBD | BSL_S_SCHANFIFO)
#define BSL_LS_BCMBD_SOCMEM             (BSL_L_BCMBD | BSL_S_SOCMEM)
#define BSL_LS_BCMBD_SOCREG             (BSL_L_BCMBD | BSL_S_SOCREG)

/* Combined layer/sources for BCMCFG layer */
#define BSL_LS_BCMCFG_COMP              (BSL_L_BCMCFG | BSL_S_COMP)
#define BSL_LS_BCMCFG_DEV               (BSL_L_BCMCFG | BSL_S_DEV)
#define BSL_LS_BCMCFG_INIT              (BSL_L_BCMCFG | BSL_S_INIT)
#define BSL_LS_BCMCFG_READ              (BSL_L_BCMCFG | BSL_S_READ)
#define BSL_LS_BCMCFG_TABLE             (BSL_L_BCMCFG | BSL_S_TABLE)

/* Combined layer/sources for BCMDRD layer */
#define BSL_LS_BCMDRD_BYPASS            (BSL_L_BCMDRD | BSL_S_BYPASS)
#define BSL_LS_BCMDRD_DEV               (BSL_L_BCMDRD | BSL_S_DEV)
#define BSL_LS_BCMDRD_HAL               (BSL_L_BCMDRD | BSL_S_HAL)

/* Combined layer/sources for BCMECN layer */
#define BSL_LS_BCMECN_ECN_PROTOCOL      (BSL_L_BCMECN | BSL_S_ECN_PROTOCOL)
#define BSL_LS_BCMECN_WRED_UPDATE       (BSL_L_BCMECN | BSL_S_WRED_UPDATE)

/* Combined layer/sources for BCMEVM layer */
#define BSL_LS_BCMEVM_EVENT             (BSL_L_BCMEVM | BSL_S_EVENT)

/* Combined layer/sources for BCMFP layer */
#define BSL_LS_BCMFP_COMMON             (BSL_L_BCMFP | BSL_S_COMMON)
#define BSL_LS_BCMFP_GRPCREATE          (BSL_L_BCMFP | BSL_S_GRPCREATE)
#define BSL_LS_BCMFP_HA                 (BSL_L_BCMFP | BSL_S_HA)
#define BSL_LS_BCMFP_INIT               (BSL_L_BCMFP | BSL_S_INIT)
#define BSL_LS_BCMFP_TRANS              (BSL_L_BCMFP | BSL_S_TRANS)

/* Combined layer/sources for BCMIMM layer */
#define BSL_LS_BCMIMM_BACKEND           (BSL_L_BCMIMM | BSL_S_BACKEND)
#define BSL_LS_BCMIMM_FRONTEND          (BSL_L_BCMIMM | BSL_S_FRONTEND)

/* Combined layer/sources for BCML2 layer */
#define BSL_LS_BCML2_LEARN_CTRL         (BSL_L_BCML2 | BSL_S_LEARN_CTRL)
#define BSL_LS_BCML2_LEARN_DRV          (BSL_L_BCML2 | BSL_S_LEARN_DRV)
#define BSL_LS_BCML2_LEARN_IMM          (BSL_L_BCML2 | BSL_S_LEARN_IMM)
#define BSL_LS_BCML2_SYSM               (BSL_L_BCML2 | BSL_S_SYSM)
#define BSL_LS_BCML2_TABLE              (BSL_L_BCML2 | BSL_S_TABLE)
#define BSL_LS_BCML2_TRANSFORM          (BSL_L_BCML2 | BSL_S_TRANSFORM)

/* Combined layer/sources for BCMLM layer */
#define BSL_LS_BCMLM_CTRL               (BSL_L_BCMLM | BSL_S_CTRL)
#define BSL_LS_BCMLM_DRV                (BSL_L_BCMLM | BSL_S_DRV)
#define BSL_LS_BCMLM_IMM                (BSL_L_BCMLM | BSL_S_IMM)
#define BSL_LS_BCMLM_INIT               (BSL_L_BCMLM | BSL_S_INIT)
#define BSL_LS_BCMLM_SYSM               (BSL_L_BCMLM | BSL_S_SYSM)

/* Combined layer/sources for BCMLRD layer */
#define BSL_LS_BCMLRD_SYSM              (BSL_L_BCMLRD | BSL_S_SYSM)

/* Combined layer/sources for BCMLT layer */
#define BSL_LS_BCMLT_ENTRY              (BSL_L_BCMLT | BSL_S_ENTRY)
#define BSL_LS_BCMLT_TABLE              (BSL_L_BCMLT | BSL_S_TABLE)
#define BSL_LS_BCMLT_TRANSACTION        (BSL_L_BCMLT | BSL_S_TRANSACTION)

/* Combined layer/sources for BCMLTM layer */
#define BSL_LS_BCMLTM_ENTRY             (BSL_L_BCMLTM | BSL_S_ENTRY)
#define BSL_LS_BCMLTM_EXECUTIONENGINE   (BSL_L_BCMLTM | BSL_S_EXECUTIONENGINE)
#define BSL_LS_BCMLTM_FIELDADAPTATION   (BSL_L_BCMLTM | BSL_S_FIELDADAPTATION)
#define BSL_LS_BCMLTM_HIGHAVAILABILITY  (BSL_L_BCMLTM | BSL_S_HIGHAVAILABILITY)
#define BSL_LS_BCMLTM_INIT              (BSL_L_BCMLTM | BSL_S_INIT)
#define BSL_LS_BCMLTM_LOGICALRESOURCEMANAGER (BSL_L_BCMLTM | BSL_S_LOGICALRESOURCEMANAGER)
#define BSL_LS_BCMLTM_METADATA          (BSL_L_BCMLTM | BSL_S_METADATA)
#define BSL_LS_BCMLTM_STATE             (BSL_L_BCMLTM | BSL_S_STATE)
#define BSL_LS_BCMLTM_TRANSACTION       (BSL_L_BCMLTM | BSL_S_TRANSACTION)

/* Combined layer/sources for BCMLTX layer */
#define BSL_LS_BCMLTX_COMMON            (BSL_L_BCMLTX | BSL_S_COMMON)
#define BSL_LS_BCMLTX_ECMP              (BSL_L_BCMLTX | BSL_S_ECMP)
#define BSL_LS_BCMLTX_EP                (BSL_L_BCMLTX | BSL_S_EP)
#define BSL_LS_BCMLTX_L2                (BSL_L_BCMLTX | BSL_S_L2)
#define BSL_LS_BCMLTX_L3                (BSL_L_BCMLTX | BSL_S_L3)
#define BSL_LS_BCMLTX_PORT              (BSL_L_BCMLTX | BSL_S_PORT)
#define BSL_LS_BCMLTX_STG               (BSL_L_BCMLTX | BSL_S_STG)
#define BSL_LS_BCMLTX_TM                (BSL_L_BCMLTX | BSL_S_TM)
#define BSL_LS_BCMLTX_TNL               (BSL_L_BCMLTX | BSL_S_TNL)
#define BSL_LS_BCMLTX_UDF               (BSL_L_BCMLTX | BSL_S_UDF)
#define BSL_LS_BCMLTX_VLAN              (BSL_L_BCMLTX | BSL_S_VLAN)

/* Combined layer/sources for BCMMETER layer */
#define BSL_LS_BCMMETER_COMMON          (BSL_L_BCMMETER | BSL_S_COMMON)
#define BSL_LS_BCMMETER_FP              (BSL_L_BCMMETER | BSL_S_FP)
#define BSL_LS_BCMMETER_INIT            (BSL_L_BCMMETER | BSL_S_INIT)
#define BSL_LS_BCMMETER_SC              (BSL_L_BCMMETER | BSL_S_SC)

/* Combined layer/sources for BCMMGMT layer */
#define BSL_LS_BCMMGMT_DEV              (BSL_L_BCMMGMT | BSL_S_DEV)
#define BSL_LS_BCMMGMT_INIT             (BSL_L_BCMMGMT | BSL_S_INIT)
#define BSL_LS_BCMMGMT_SYSM             (BSL_L_BCMMGMT | BSL_S_SYSM)

/* Combined layer/sources for BCMMIRROR layer */
#define BSL_LS_BCMMIRROR_COMMON         (BSL_L_BCMMIRROR | BSL_S_COMMON)
#define BSL_LS_BCMMIRROR_DEV            (BSL_L_BCMMIRROR | BSL_S_DEV)
#define BSL_LS_BCMMIRROR_INIT           (BSL_L_BCMMIRROR | BSL_S_INIT)

/* Combined layer/sources for BCMPC layer */
#define BSL_LS_BCMPC_DB                 (BSL_L_BCMPC | BSL_S_DB)
#define BSL_LS_BCMPC_DEV                (BSL_L_BCMPC | BSL_S_DEV)
#define BSL_LS_BCMPC_IMM                (BSL_L_BCMPC | BSL_S_IMM)
#define BSL_LS_BCMPC_INIT               (BSL_L_BCMPC | BSL_S_INIT)
#define BSL_LS_BCMPC_LPORT              (BSL_L_BCMPC | BSL_S_LPORT)
#define BSL_LS_BCMPC_LTH                (BSL_L_BCMPC | BSL_S_LTH)
#define BSL_LS_BCMPC_PHYMOD             (BSL_L_BCMPC | BSL_S_PHYMOD)
#define BSL_LS_BCMPC_PM                 (BSL_L_BCMPC | BSL_S_PM)
#define BSL_LS_BCMPC_PMGR               (BSL_L_BCMPC | BSL_S_PMGR)
#define BSL_LS_BCMPC_TOPO               (BSL_L_BCMPC | BSL_S_TOPO)

/* Combined layer/sources for BCMPKT layer */
#define BSL_LS_BCMPKT_DEV               (BSL_L_BCMPKT | BSL_S_DEV)
#define BSL_LS_BCMPKT_DMA               (BSL_L_BCMPKT | BSL_S_DMA)
#define BSL_LS_BCMPKT_HIGIG             (BSL_L_BCMPKT | BSL_S_HIGIG)
#define BSL_LS_BCMPKT_KNET              (BSL_L_BCMPKT | BSL_S_KNET)
#define BSL_LS_BCMPKT_LBHDR             (BSL_L_BCMPKT | BSL_S_LBHDR)
#define BSL_LS_BCMPKT_NET               (BSL_L_BCMPKT | BSL_S_NET)
#define BSL_LS_BCMPKT_PACKET            (BSL_L_BCMPKT | BSL_S_PACKET)
#define BSL_LS_BCMPKT_RX                (BSL_L_BCMPKT | BSL_S_RX)
#define BSL_LS_BCMPKT_RXPMD             (BSL_L_BCMPKT | BSL_S_RXPMD)
#define BSL_LS_BCMPKT_TX                (BSL_L_BCMPKT | BSL_S_TX)
#define BSL_LS_BCMPKT_TXPMD             (BSL_L_BCMPKT | BSL_S_TXPMD)
#define BSL_LS_BCMPKT_UNET              (BSL_L_BCMPKT | BSL_S_UNET)

/* Combined layer/sources for BCMPORT layer */
#define BSL_LS_BCMPORT_IMM              (BSL_L_BCMPORT | BSL_S_IMM)
#define BSL_LS_BCMPORT_MIRROR           (BSL_L_BCMPORT | BSL_S_MIRROR)
#define BSL_LS_BCMPORT_PORT_BRIDGE      (BSL_L_BCMPORT | BSL_S_PORT_BRIDGE)
#define BSL_LS_BCMPORT_PORT_MEMBERSHIP_POLICY (BSL_L_BCMPORT | BSL_S_PORT_MEMBERSHIP_POLICY)
#define BSL_LS_BCMPORT_SYSM             (BSL_L_BCMPORT | BSL_S_SYSM)
#define BSL_LS_BCMPORT_TABLE            (BSL_L_BCMPORT | BSL_S_TABLE)

/* Combined layer/sources for BCMPTM layer */
#define BSL_LS_BCMPTM_CACHE             (BSL_L_BCMPTM | BSL_S_CACHE)
#define BSL_LS_BCMPTM_CCI               (BSL_L_BCMPTM | BSL_S_CCI)
#define BSL_LS_BCMPTM_CTHALPM           (BSL_L_BCMPTM | BSL_S_CTHALPM)
#define BSL_LS_BCMPTM_CTHUFT            (BSL_L_BCMPTM | BSL_S_CTHUFT)
#define BSL_LS_BCMPTM_ENTRY             (BSL_L_BCMPTM | BSL_S_ENTRY)
#define BSL_LS_BCMPTM_IREQ              (BSL_L_BCMPTM | BSL_S_IREQ)
#define BSL_LS_BCMPTM_METADATA          (BSL_L_BCMPTM | BSL_S_METADATA)
#define BSL_LS_BCMPTM_MISC              (BSL_L_BCMPTM | BSL_S_MISC)
#define BSL_LS_BCMPTM_MREQ              (BSL_L_BCMPTM | BSL_S_MREQ)
#define BSL_LS_BCMPTM_PHYSICALRESOURCEMANAGER (BSL_L_BCMPTM | BSL_S_PHYSICALRESOURCEMANAGER)
#define BSL_LS_BCMPTM_RMALPM            (BSL_L_BCMPTM | BSL_S_RMALPM)
#define BSL_LS_BCMPTM_RMALPMTRIE        (BSL_L_BCMPTM | BSL_S_RMALPMTRIE)
#define BSL_LS_BCMPTM_RMHASH            (BSL_L_BCMPTM | BSL_S_RMHASH)
#define BSL_LS_BCMPTM_RMTCAM            (BSL_L_BCMPTM | BSL_S_RMTCAM)
#define BSL_LS_BCMPTM_SER               (BSL_L_BCMPTM | BSL_S_SER)
#define BSL_LS_BCMPTM_TRANSACTION       (BSL_L_BCMPTM | BSL_S_TRANSACTION)
#define BSL_LS_BCMPTM_UFT               (BSL_L_BCMPTM | BSL_S_UFT)
#define BSL_LS_BCMPTM_WAL               (BSL_L_BCMPTM | BSL_S_WAL)

/* Combined layer/sources for BCMTM layer */
#define BSL_LS_BCMTM_                   (BSL_L_BCMTM | BSL_S_)
#define BSL_LS_BCMTM_INIT               (BSL_L_BCMTM | BSL_S_INIT)
#define BSL_LS_BCMTM_LTH                (BSL_L_BCMTM | BSL_S_LTH)
#define BSL_LS_BCMTM_TMMGR              (BSL_L_BCMTM | BSL_S_TMMGR)

/* Combined layer/sources for BCMTNL layer */
#define BSL_LS_BCMTNL_COMMON            (BSL_L_BCMTNL | BSL_S_COMMON)

/* Combined layer/sources for BCMTRM layer */
#define BSL_LS_BCMTRM_ENTRY             (BSL_L_BCMTRM | BSL_S_ENTRY)
#define BSL_LS_BCMTRM_TRANSACTION       (BSL_L_BCMTRM | BSL_S_TRANSACTION)

/* Combined layer/sources for BCMTRUNK layer */
#define BSL_LS_BCMTRUNK_SYSM            (BSL_L_BCMTRUNK | BSL_S_SYSM)
#define BSL_LS_BCMTRUNK_TABLE           (BSL_L_BCMTRUNK | BSL_S_TABLE)

/* Combined layer/sources for SHR layer */
#define BSL_LS_SHR_AVL                  (BSL_L_SHR | BSL_S_AVL)
#define BSL_LS_SHR_BITOP                (BSL_L_SHR | BSL_S_BITOP)
#define BSL_LS_SHR_GDATA                (BSL_L_SHR | BSL_S_GDATA)
#define BSL_LS_SHR_HA                   (BSL_L_SHR | BSL_S_HA)
#define BSL_LS_SHR_SYSM                 (BSL_L_SHR | BSL_S_SYSM)

/* Combined layer/sources for SYS layer */
#define BSL_LS_SYS_DMA                  (BSL_L_SYS | BSL_S_DMA)
#define BSL_LS_SYS_INTR                 (BSL_L_SYS | BSL_S_INTR)
#define BSL_LS_SYS_KNET                 (BSL_L_SYS | BSL_S_KNET)
#define BSL_LS_SYS_PACKET               (BSL_L_SYS | BSL_S_PACKET)
#define BSL_LS_SYS_PCI                  (BSL_L_SYS | BSL_S_PCI)
#define BSL_LS_SYS_RX                   (BSL_L_SYS | BSL_S_RX)
#define BSL_LS_SYS_TPACKET              (BSL_L_SYS | BSL_S_TPACKET)
#define BSL_LS_SYS_TX                   (BSL_L_SYS | BSL_S_TX)
#define BSL_LS_SYS_UNET                 (BSL_L_SYS | BSL_S_UNET)
#define BSL_LS_SYS_VERINET              (BSL_L_SYS | BSL_S_VERINET)

#define BSL_SOURCES_VALID_DEF(type_) \
static type_ bsl_source_appl_valid[] = BSL_SOURCE_APPL_VALID_INIT; \
static type_ bsl_source_bcmbd_valid[] = BSL_SOURCE_BCMBD_VALID_INIT; \
static type_ bsl_source_bcmcfg_valid[] = BSL_SOURCE_BCMCFG_VALID_INIT; \
static type_ bsl_source_bcmdrd_valid[] = BSL_SOURCE_BCMDRD_VALID_INIT; \
static type_ bsl_source_bcmecn_valid[] = BSL_SOURCE_BCMECN_VALID_INIT; \
static type_ bsl_source_bcmevm_valid[] = BSL_SOURCE_BCMEVM_VALID_INIT; \
static type_ bsl_source_bcmfp_valid[] = BSL_SOURCE_BCMFP_VALID_INIT; \
static type_ bsl_source_bcmimm_valid[] = BSL_SOURCE_BCMIMM_VALID_INIT; \
static type_ bsl_source_bcml2_valid[] = BSL_SOURCE_BCML2_VALID_INIT; \
static type_ bsl_source_bcmlm_valid[] = BSL_SOURCE_BCMLM_VALID_INIT; \
static type_ bsl_source_bcmlrd_valid[] = BSL_SOURCE_BCMLRD_VALID_INIT; \
static type_ bsl_source_bcmlt_valid[] = BSL_SOURCE_BCMLT_VALID_INIT; \
static type_ bsl_source_bcmltm_valid[] = BSL_SOURCE_BCMLTM_VALID_INIT; \
static type_ bsl_source_bcmltx_valid[] = BSL_SOURCE_BCMLTX_VALID_INIT; \
static type_ bsl_source_bcmmeter_valid[] = BSL_SOURCE_BCMMETER_VALID_INIT; \
static type_ bsl_source_bcmmgmt_valid[] = BSL_SOURCE_BCMMGMT_VALID_INIT; \
static type_ bsl_source_bcmmirror_valid[] = BSL_SOURCE_BCMMIRROR_VALID_INIT; \
static type_ bsl_source_bcmpc_valid[] = BSL_SOURCE_BCMPC_VALID_INIT; \
static type_ bsl_source_bcmpkt_valid[] = BSL_SOURCE_BCMPKT_VALID_INIT; \
static type_ bsl_source_bcmport_valid[] = BSL_SOURCE_BCMPORT_VALID_INIT; \
static type_ bsl_source_bcmptm_valid[] = BSL_SOURCE_BCMPTM_VALID_INIT; \
static type_ bsl_source_bcmtm_valid[] = BSL_SOURCE_BCMTM_VALID_INIT; \
static type_ bsl_source_bcmtnl_valid[] = BSL_SOURCE_BCMTNL_VALID_INIT; \
static type_ bsl_source_bcmtrm_valid[] = BSL_SOURCE_BCMTRM_VALID_INIT; \
static type_ bsl_source_bcmtrunk_valid[] = BSL_SOURCE_BCMTRUNK_VALID_INIT; \
static type_ bsl_source_shr_valid[] = BSL_SOURCE_SHR_VALID_INIT; \
static type_ bsl_source_sys_valid[] = BSL_SOURCE_SYS_VALID_INIT


#define BSL_SOURCES_VALID_INIT { \
    bsl_source_appl_valid, \
    bsl_source_bcmbd_valid, \
    bsl_source_bcmcfg_valid, \
    bsl_source_bcmdrd_valid, \
    bsl_source_bcmecn_valid, \
    bsl_source_bcmevm_valid, \
    bsl_source_bcmfp_valid, \
    bsl_source_bcmimm_valid, \
    bsl_source_bcml2_valid, \
    bsl_source_bcmlm_valid, \
    bsl_source_bcmlrd_valid, \
    bsl_source_bcmlt_valid, \
    bsl_source_bcmltm_valid, \
    bsl_source_bcmltx_valid, \
    bsl_source_bcmmeter_valid, \
    bsl_source_bcmmgmt_valid, \
    bsl_source_bcmmirror_valid, \
    bsl_source_bcmpc_valid, \
    bsl_source_bcmpkt_valid, \
    bsl_source_bcmport_valid, \
    bsl_source_bcmptm_valid, \
    bsl_source_bcmtm_valid, \
    bsl_source_bcmtnl_valid, \
    bsl_source_bcmtrm_valid, \
    bsl_source_bcmtrunk_valid, \
    bsl_source_shr_valid, \
    bsl_source_sys_valid, \
    NULL \
}

#endif /* BSL_CONFIG_INCLUDE_CUSTOM_ENUM */

#endif /* BSL_ENUM_H */
